### ISSUE TITLE
"Something went wrong" when renewing certificates

### ISSUE THREAD

**Issue by DecentM** [mail-in-a-box/mailinabox#1104]
A few weeks ago, out of the blue, my box stopped being able to renew certificates automatically through letsencrypt. It then hit the 5 / week limit, so just now, I added another domain to be able to get certs again.
I was able to reproduce the problem this way, and this popped up in /var/log/syslog
```
Exception on /ssl/provision [POST]#012Traceback (most recent call last):#012
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app#012
      response = self.full_dispatch_request()#012
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request#012
      rv = self.handle_user_exception(e)#012
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception#012
      reraise(exc_type, exc_value, tb)#012
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012
      raise value#012
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request#012
      rv = self.dispatch_request()#012
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request#012
      return self.view_functions[rule.endpoint](**req.view_args)#012
  File "/usr/local/bin/mailinabox-daemon", line 55, in newview#012
      return viewfunc(*args, **kwargs)#012
  File "/usr/local/bin/mailinabox-daemon", line 384, in ssl_provision_certs#012
      jsonable=True)#012
  File "/home/decentm/mailinabox/management/ssl_certificates.py", line 337, in provision_certificates#012
      logger=my_logger)#012
  File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 76, in issue_certificate#012
      (cert_pem, chain) = request_certificate_issuance(client, challenges, csr, logger)#012
  File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 210, in request_certificate_issuance#012
      cert_pem = cert_to_pem(cert_response.body)#012
  File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 217, in cert_to_pem#012
      return OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)#012TypeError: must be X509, not ComparableX509
```
So far, I've tried rebooting the box, re-running the mailinabox command, the installer, and deleting the ssl directory. None of these seem to fix the problem.

The only packages that are on the box are the ones MIAB installed, plus these: ``zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl``, because I run [netdata](https://my-netdata.io/) on the box. It reports usage and load stats much like Munin, and doesn't interfere with MIAB.

EDIT: Now that I think about it, this started about the time I updated to 0.21c

**Comment by jalogisch** [comment]
please check if this will solve your issue: https://github.com/mail-in-a-box/mailinabox/issues/1101#issuecomment-281026627

**Comment by DecentM** [comment]
Wow, yes it actually does, thank you!
Really odd that the uninstall had to be ran twice, I think that tripped it up.
