### ISSUE TITLE
Major SSL issues

### ISSUE THREAD

**Issue by nikolay** [mail-in-a-box/mailinabox#1117]
My certs did not autoupdate. When I try to autoupdate via the "Provision" button, I get some generic error and nothing happens and there's no way for me to fix this. Any idea?

**Comment by stan3** [comment]
Anything like #1101?

**Comment by cromulus** [comment]
What is the error?

**Comment by nikolay** [comment]
```
Something unexpected went wrong: Error creating new cert :: Too many certificates already issued for exact set of domains: bgschool.com,box.cherkva.org,bulgarianfest.com,bulgarianfest.org,bulgarianfestival.com,bulgarianfestival.org,cherkva.com,cherkva.org,saintzlata.com,saintzlata.org,stzlata.com,stzlata.org,svetazlata.com,svetazlata.org,svzlata.com,svzlata.org,www.bgschool.com,www.bulgarianfest.com,www.bulgarianfest.org,www.bulgarianfestival.com,www.bulgarianfestival.org,www.cherkva.com,www.cherkva.org,www.saintzlata.com,www.saintzlata.org,www.stzlata.com,www.stzlata.org,www.svetazlata.com,www.svetazlata.org,www.svzlata.com,www.svzlata.org

Log:
Reading account key from /home/user-data/ssl/lets_encrypt/account.pem.
Validating existing account saved to /home/user-data/ssl/lets_encrypt/registration.json.
Reusing existing challenges for box.cherkva.org.
The challenges for box.cherkva.org have been accepted.
Reusing existing challenges for cherkva.org.
The challenges for cherkva.org have been accepted.
Reusing existing challenges for www.cherkva.org.
The challenges for www.cherkva.org have been accepted.
Reusing existing challenges for bgschool.com.
The challenges for bgschool.com have been accepted.
Reusing existing challenges for www.bgschool.com.
The challenges for www.bgschool.com have been accepted.
Reusing existing challenges for bulgarianfest.com.
The challenges for bulgarianfest.com have been accepted.
Reusing existing challenges for www.bulgarianfest.com.
The challenges for www.bulgarianfest.com have been accepted.
Reusing existing challenges for bulgarianfest.org.
The challenges for bulgarianfest.org have been accepted.
Reusing existing challenges for www.bulgarianfest.org.
The challenges for www.bulgarianfest.org have been accepted.
Reusing existing challenges for bulgarianfestival.com.
The challenges for bulgarianfestival.com have been accepted.
Reusing existing challenges for www.bulgarianfestival.com.
The challenges for www.bulgarianfestival.com have been accepted.
Reusing existing challenges for bulgarianfestival.org.
The challenges for bulgarianfestival.org have been accepted.
Reusing existing challenges for www.bulgarianfestival.org.
The challenges for www.bulgarianfestival.org have been accepted.
Reusing existing challenges for cherkva.com.
The challenges for cherkva.com have been accepted.
Reusing existing challenges for www.cherkva.com.
The challenges for www.cherkva.com have been accepted.
Reusing existing challenges for saintzlata.com.
The challenges for saintzlata.com have been accepted.
Reusing existing challenges for www.saintzlata.com.
The challenges for www.saintzlata.com have been accepted.
Reusing existing challenges for saintzlata.org.
The challenges for saintzlata.org have been accepted.
Reusing existing challenges for www.saintzlata.org.
The challenges for www.saintzlata.org have been accepted.
Reusing existing challenges for stzlata.com.
The challenges for stzlata.com have been accepted.
Reusing existing challenges for www.stzlata.com.
The challenges for www.stzlata.com have been accepted.
Reusing existing challenges for stzlata.org.
The challenges for stzlata.org have been accepted.
Reusing existing challenges for www.stzlata.org.
The challenges for www.stzlata.org have been accepted.
Reusing existing challenges for svetazlata.com.
The challenges for svetazlata.com have been accepted.
Reusing existing challenges for www.svetazlata.com.
The challenges for www.svetazlata.com have been accepted.
Reusing existing challenges for svetazlata.org.
The challenges for svetazlata.org have been accepted.
Reusing existing challenges for www.svetazlata.org.
The challenges for www.svetazlata.org have been accepted.
Reusing existing challenges for svzlata.com.
The challenges for svzlata.com have been accepted.
Reusing existing challenges for www.svzlata.com.
The challenges for www.svzlata.com have been accepted.
Reusing existing challenges for svzlata.org.
The challenges for svzlata.org have been accepted.
Reusing existing challenges for www.svzlata.org.
The challenges for www.svzlata.org have been accepted.
Generating a new certificate signing request.
Requesting a certificate.
```

**Comment by yodax** [comment]
Are you on the latest version? It seems that you have been rate limited. You are requesting quite a lot of domains. 

See [here](https://letsencrypt.org/docs/rate-limits/)

**Comment by nikolay** [comment]
Latest. Thrse are just a few. There should be a batch process and not
submitting all at once.

**Comment by yodax** [comment]
Did you read the link I posted? Specifically this part:

>If you’ve hit a rate limit, we don’t have a way to temporarily reset it. You’ll need to wait until the rate limit expires after a week. We use a sliding window, so if you issued 10 certificates on Monday and 10 more certificates on Friday, you’ll be able to issue again starting Monday. You can get a list of certificates issued for your registered domain by searching on crt.sh, which uses the public Certificate Transparency logs.

You should at least by able to trace why you hit the rate limit

**Comment by nikolay** [comment]
Yeah, I read it, but you don't seem to try 10 at a time - you try all at
the same time.

**Comment by yodax** [comment]
Yes we do, however that shouldn't affect rate limiting. Even if you add a domain a week, whenever a domain gets added to a previously issued not expired cert you get a non rate limited response.

**Comment by nikolay** [comment]
@yodax Can you guys help? Same issue with v0.22! This has nothing to do with my domains, but with the way you submit the requests. If there's no support for more than N domains, make this obvious, but now I'm in a stuck state and several non-profits cannot check their emails.

**Comment by stan3** [comment]
@nikolay I think we need more details on what you've tried. Did you read through the issue I referenced?  Do you have the package python3-openssl installed (it shouldn't be)?

**Comment by nikolay** [comment]
@stan3 I do have that installed because it was recommended at some point due to another issue.

**Comment by nikolay** [comment]
@stan3 I tried to uninstall and purge it (as suggested earlier when there was another issue):

```
root@box:~# apt-get -y purge python3-openssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  python3-openssl*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 427 kB disk space will be freed.
(Reading database ... 105626 files and directories currently installed.)
Removing python3-openssl (0.13-2ubuntu6) ...
root@box:~# rm -rf /usr/local/lib/python3.4/dist-packages/{OpenSSL,cryptography}*
```

Then, I rerun the setup, but then it complained like this:

```
updated DNS: OpenDKIM configuration
Traceback (most recent call last):
  File "management/ssl_certificates.py", line 809, in <module>
    provision_certificates_cmdline()
  File "management/ssl_certificates.py", line 452, in provision_certificates_cmdline
    status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
  File "management/ssl_certificates.py", line 272, in provision_certificates
    import acme.messages
  File "/usr/local/lib/python3.4/dist-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/local/lib/python3.4/dist-packages/acme/challenges.py", line 9, in <module>
    import OpenSSL
ImportError: No module named 'OpenSSL'
```

So, I had to reinstall it and rerun the setup, but around the end, it complained again:

```
box.cherkva.org, cherkva.org, www.cherkva.org, bgschool.com, www.bgschool.com, bulgarianfest.com, www.bulgarianfest.com, bulgarianfest.org, www.bulgarianfest.org, bulgarianfestival.com, www.bulgarianfestival.com, bulgarianfestival.org, www.bulgarianfestival.org, cherkva.com, www.cherkva.com, saintzlata.com, www.saintzlata.com, saintzlata.org, www.saintzlata.org, stzlata.com, www.stzlata.com, stzlata.org, www.stzlata.org, svetazlata.com, www.svetazlata.com, svetazlata.org, www.svetazlata.org, svzlata.com, www.svzlata.com, svzlata.org, www.svzlata.org:
Something unexpected went wrong: Error creating new cert :: too many certificates already issued for exact set of domains: bgschool.com,box.cherkva.org,bulgarianfest.com,bulgarianfest.org,bulgarianfestival.com,bulgarianfestival.org,cherkva.com,cherkva.org,saintzlata.com,saintzlata.org,stzlata.com,stzlata.org,svetazlata.com,svetazlata.org,svzlata.com,svzlata.org,www.bgschool.com,www.bulgarianfest.com,www.bulgarianfest.org,www.bulgarianfestival.com,www.bulgarianfestival.org,www.cherkva.com,www.cherkva.org,www.saintzlata.com,www.saintzlata.org,www.stzlata.com,www.stzlata.org,www.svetazlata.com,www.svetazlata.org,www.svzlata.com,www.svzlata.org
```

**Comment by stan3** [comment]
So I believe you want the pip installed python openssl rather than the package one.   The similar bug I had was due to the packaged version being installed caused the letsencrypt provisioning to keep failing and then hit their rate limit.  The workaround for me was running "management/ssl_certificates.py" with a different set of domains (as mentioned in linked threads).

**Comment by nikolay** [comment]
In such case, running the installer should see that OpenSSL is missing and
install it the proper way - it doesn't seem to do it right now.

**Comment by nikolay** [comment]
@stan3 I uninstalled python-openssl and python3-openssl and re-run the installer. I don't see an OpenSSL error anymore, but the `Error creating new cert :: too many certificates already issued for exact set of domains` error still exists.

**Comment by nikolay** [comment]
@stan3 I managed to work around the blocker - simply added a new domain and as the set has changed, Let's Encrypt pass it through. I think Mail-in-a-box should handle this (although not automatically) - allow a domain to be excluded so people can submit or possibly enable the creation of different groups.
