### ISSUE TITLE
System status page broke with v0.22

### ISSUE THREAD

**Issue by c0nk** [mail-in-a-box/mailinabox#1134]
System Status Checks page doesn't load. It simply prints "Something went wrong, sorry.". Enabling/disabling New-Version Check has no affect.

**Comment by yodax** [comment]
Could you run it from the command line? management/status_checks.py

**Comment by c0nk** [comment]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "mailinabox/management/status_checks.py", line 344, in run_domain_checks_on_domain
    check_primary_hostname_dns(domain, env, output, dns_domains, dns_zonefiles)
  File "mailinabox/management/status_checks.py", line 396, in check_primary_hostname_dns
    if ip == env['PUBLIC_IP'] and not (ipv6 and env['PUBLIC_IPV6'] and normalize_ip(ipv6) != normalize_ip(env['PUBLIC_IPV6'])):
  File "mailinabox/management/status_checks.py", line 897, in normalize_ip
    return str(ipaddress.ip_address(ip))
  File "/usr/lib/python3.4/ipaddress.py", line 54, in ip_address
    address)
ValueError: '[Not Set]' does not appear to be an IPv4 or IPv6 address
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mailinabox/management/status_checks.py", line 980, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "mailinabox/management/status_checks.py", line 65, in run_checks
    run_domain_checks(rounded_values, env, output, pool)
  File "mailinabox/management/status_checks.py", line 323, in run_domain_checks
    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
ValueError: '[Not Set]' does not appear to be an IPv4 or IPv6 address
```

**Comment by yodax** [comment]
Looks to be related to https://github.com/mail-in-a-box/mailinabox/pull/1052

```
File "mailinabox/management/status_checks.py", line 897, in normalize_ip
    return str(ipaddress.ip_address(ip))
```

However I'm not sure. I don't have time at this moment to investigate properly. Maybe later today.

**Comment by c0nk** [comment]
I am using a custom DNS setup. I remember it used to print "[Not Set]" for the missing DNS entries. It could be related to this.

**Comment by yodax** [comment]
Sounds plausible.

**Comment by JoshData** [comment]
Paging @Jonchun.

**Comment by Jonchun** [comment]
Taking a look at this.

**Comment by Jonchun** [comment]
From an initial look I think its an unexpected case that I didn't expect. I quick fix can be done by checking for the "[Not Set]" string but I'm going to do a little digging to see if there's a cleaner way. Thoughts @joshdata @yodax?

**Comment by yodax** [comment]
We can either wrap the call or check for not set. I don't mind either way. I'll gladly defer to @JoshData for this.

**Comment by JoshData** [comment]
The best thing is probably to put a try/except in normalize_ip so that the function *never* raises an exception. If it can't normalize the address, it should return the original value unchanged.

**Comment by yodax** [comment]
I created a PR for this; if someone could test, that would be great since I don't have the issue. Please see: https://github.com/mail-in-a-box/mailinabox/pull/1139

**Comment by c0nk** [comment]
Your PR fixes my issue.

**Comment by JoshData** [comment]
Thanks everyone. I'll post a new release once the other bug (rsync) is fixed.
