### ISSUE TITLE
python ./mail_log.py

### ISSUE THREAD

**Issue by NitescuLucian** [mail-in-a-box/mailinabox#1145]
When i run:
python ./mail_log.py

I get:
 File "./mail_log.py", line 7, in <module>
    import dateutil.parser

**Comment by NitescuLucian** [comment]
I have updated:
```

root@box:~/fail/mailinabox/management# ./mail_log.py
Scanning from 2017-04-05 15:49:47 back to 2017-04-05 00:00:00
Processing file /var/log/mail.log ...
Traceback (most recent call last):
  File "./mail_log.py", line 881, in <module>
    scan_mail_log(env_vars)
  File "./mail_log.py", line 127, in scan_mail_log
    scan_files(collector)
  File "./mail_log.py", line 83, in scan_files
    if scan_mail_log_line(line.strip(), collector) is False:
  File "./mail_log.py", line 334, in scan_mail_log_line
    date = datetime.datetime.strptime(date, '%b %d %H:%M:%S')
  File "/usr/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data 'AApr 05 09:10:50' does not match format '%b %d %H:%M:%S
```'

**Comment by NitescuLucian** [comment]
same as #1146
