### ISSUE TITLE
Nextcloud Sabre error

### ISSUE THREAD

**Issue by dofl** [mail-in-a-box/mailinabox#1219]
I'm investigating high CPU usage on my server since June without any changes in users, etc. and I found this error in the nextcloud.log.

Something is requesting info, but fails? It's a local process, but I coudn't identify which one. Could it be z-push? Any idea on how to investigate further?

{"reqId":"89Om6aureDzvUg74N\/DZ","remoteAddr":"127.0.0.1","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/lib\\\/...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-07-26 15:07:24","method":"OPTIONS","url":"\/cloud\/remote.php\/caldav\/calendars\/<my@e-mailaddress.com>\/","user":"--","version":"9.1.5.2"}

{"reqId":"Q0XPvE\/CalvkstD2wCi\/","remoteAddr":"127.0.0.1","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/lib\\\/...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-07-26 15:07:25","method":"OPTIONS","url":"\/cloud\/remote.php\/carddav\/addressbooks\/<my@e-mailaddress.com>\/","user":"--","version":"9.1.5.2"}

{"reqId":"7IyXufceKW29+3NUcclr","remoteAddr":"127.0.0.1","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/lib\\\/...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-07-26 15:08:11","method":"OPTIONS","url":"\/cloud\/remote.php\/caldav\/calendars\/<my@e-mailaddress.com>\/","user":"--","version":"9.1.5.2"}

{"reqId":"Ol6p2l7q24j19kiHFdvD","remoteAddr":"127.0.0.1","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/carddav.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/local\\\/lib\\\/owncloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/lib\\\/...')\\n#6 {main}\",\"File\":\"\\\/usr\\\/local\\\/lib\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2017-07-26 15:08:12","method":"OPTIONS","url":"\/cloud\/remote.php\/carddav\/addressbooks\/<my@e-mailaddress.com>\/","user":"--","version":"9.1.5.2"}

**Comment by yodax** [comment]
Which version of NextCloud are you on? The one from master?

**Comment by dofl** [comment]
Yes, Nextcloud 10.0.5 (stable)

**Comment by dofl** [comment]
I found some similar problems in this topic: https://help.nextcloud.com/t/after-11-upgrade-sabre-web-dav-error-in-log/7361

It could be or Davdroid again, or Rainloop. But it's error's are with the sync of carddav as well as the caldav.

**Comment by yodax** [comment]
Master is on version 12, you could try that. It does seem like an external not sending the correct authentication. I saw something similar on the forum a while back.

**Comment by dofl** [comment]
I'm only updating based on releases, I thought you meant the latest release. My fault.
It's annoying as logs are unusable because of the recurring error and there is no information on what it could be.

**Comment by yodax** [comment]
I found the topic: https://discourse.mailinabox.email/t/authentication-error-for-one-user-help-to-debug/2334

No solution though
