### ISSUE TITLE
Cant get ssl certificate: Something went wrong

### ISSUE THREAD

**Issue by yorannic** [mail-in-a-box/mailinabox#1325]
I tried getting a ssl certificate but i get this error:

Traceback (most recent call last):
  File "management/ssl_certificates.py", line 803, in <module>
    provision_certificates_cmdline()
  File "management/ssl_certificates.py", line 446, in provision_certificates_cmdline
    status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
  File "management/ssl_certificates.py", line 331, in provision_certificates
    logger=my_logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 64, in issue_certificate
    agree_to_tos_url, validation_method, acme_server, logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 112, in validate_domain_ownership
    acme_server=acme_server)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certificates/client.py", line 317, in create_client
    client = acme.client.Client(acme_server, key)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/acme/client.py", line 72, in __init__
    self.net.get(directory).json())
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/acme/client.py", line 681, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/acme/client.py", line 630, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)

anyone can help me pls?

**Comment by xetorixik** [comment]
This is a known problem as written over here: https://github.com/mail-in-a-box/mailinabox/issues/1328
Switch to the master branch and run the setup again.

**Comment by JoshData** [comment]
From the information above it appears this was a network problem and not an issue with Mail-in-a-Box, but look out for some upcoming changes to how we provision certificates that should make it more stable.
