### ISSUE TITLE
error in run_duplicity_verification() backup.py

### ISSUE THREAD

**Issue by mahanmp** [mail-in-a-box/mailinabox#1331]
I'm currently using MIAB v0.26

My backups suddenly didn't work and i checked the error by running manually the backup in the console using 

`management/backup.py --status --verify`

and this is the error log

```
Using temporary directory /tmp/duplicity-lgJRQe-tempdir
Difference found: File mail/roundcube has mtime Sat Jan 20 10:22:23 2018, expected Sat Jan 20 08:51:36 2018
Difference found: File mail/roundcube/roundcube.sqlite has mtime Sat Jan 20 10:22:23 2018, expected Sat Jan 20 08:51:36 2018
Difference found: File owncloud has mtime Sat Jan 20 10:17:11 2018, expected Sat Jan 20 08:17:04 2018
Difference found: File owncloud/owncloud.db has mtime Sat Jan 20 10:17:11 2018, expected Sat Jan 20 08:17:04 2018
Deleting /tmp/duplicity-lgJRQe-tempdir/mktemp-omBerl-3
Processed volume 1 of 4
Deleting /tmp/duplicity-lgJRQe-tempdir/mktemp-2riiRa-4
Processed volume 2 of 4
Deleting /tmp/duplicity-lgJRQe-tempdir/mktemp-w9rGXQ-1
Processed volume 3 of 4
Deleting /tmp/duplicity-lgJRQe-tempdir/mktemp-VVPW82-2
Processed volume 4 of 4
Verify complete: 40037 files compared, 4 differences found.
Traceback (most recent call last):
  File "management/backup.py", line 556, in <module>
    run_duplicity_verification()
  File "management/backup.py", line 374, in run_duplicity_verification
    ] + rsync_ssh_options, get_env(env))
  File "/root/mailinabox/management/utils.py", line 123, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/duplicity', '--verbosity', 'info', 'verify', '--compare-data', '--archive-dir', '/home/user-data/backup/cache', '--exclude', '/home/user-data/backup', 'file:///home/user-data/backup/encrypted', '/home/user-data', "--ssh-options='-i /root/.ssh/id_rsa_miab' -p 6035", '--rsync-options=-e "/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 6035 -i /root/.ssh/id_rsa_miab"']' returned non-zero exit status 1
```

I tested the rsync connection and i can login on my backup account on miab box without any problems

This is my first time setting my backups in rsync in this server.

P.S. I edited slightly the backup.py by adding adding 6035 port

**Comment by aroundmyroom** [comment]
did you got a solution? I see the same issue but dunno where it is related to
