### ISSUE TITLE
some certificate notification and ImportError at the end of installation

### ISSUE THREAD

**Issue by ali3seven** [mail-in-a-box/mailinabox#1332]
Before the installation become complete, here was something about certificate it seems.
However installation was completed and right after that ask me about owner password and confirm it.
I can also login to the box. however here is the log.
it seems certificate valid for just 1 year. Is that OK too?
```
updated DNS: xyz.domain.com
web updated
Traceback (most recent call last):
  File "management/ssl_certificates.py", line 803, in <module>
    provision_certificates_cmdline()
  File "management/ssl_certificates.py", line 446, in provision_certificates_cmd                                                                                        line
    status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logg                                                                                        er=my_logger, force_domains=force_domains, show_extended_problems=show_extended_                                                                                        problems)
  File "management/ssl_certificates.py", line 331, in provision_certificates
    logger=my_logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certi                                                                                        ficates/client.py", line 64, in issue_certificate
    agree_to_tos_url, validation_method, acme_server, logger)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certi                                                                                        ficates/client.py", line 112, in validate_domain_ownership
    acme_server=acme_server)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certi                                                                                        ficates/client.py", line 314, in create_client
    key = load_or_generate_private_key(account_key_file, log)
  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/free_tls_certi                                                                                        ficates/client.py", line 337, in load_or_generate_private_key
    from acme import jose
ImportError: cannot import name 'jose'
```
Thanks

**Comment by e-fu** [comment]
same here.

**Comment by xetorixik** [comment]
This is a known problem as written over here: https://github.com/mail-in-a-box/mailinabox/issues/1328
Switch to the master branch and run the setup again.
