### ISSUE TITLE
local variable 'system_certificate' referenced before assignment

### ISSUE THREAD

**Issue by Vinajb** [mail-in-a-box/mailinabox#1392]
```
Jul  4 01:18:37 mail Exception on /ssl/status [GET]#012Traceback (most recent call last):
#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app
#012    response = self.full_dispatch_request()
#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request
#012    rv = self.handle_user_exception(e)
#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception
#012    reraise(exc_type, exc_value, tb)
#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/_compat.py", line 35, in reraise
#012    raise value
#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request
#012    rv = self.dispatch_request()
#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request
#012    return self.view_functions[rule.endpoint](**req.view_args)
#012  File "/home/vincent/mailinabox/management/daemon.py", line 53, in newview
#012    return viewfunc(*args, **kwargs)
#012  File "/home/vincent/mailinabox/management/daemon.py", line 336, in ssl_get_status
#012    provision, cant_provision = get_certificates_to_provision(env, show_valid_certs=False)
#012  File "/home/vincent/mailinabox/management/ssl_certificates.py", line 228, in get_certificates_to_provision
#012    existing_cert = get_domain_ssl_files(domain, existing_certs, env, use_main_cert=False)
#012  File "/home/vincent/mailinabox/management/ssl_certificates.py", line 168, in get_domain_ssl_files
#012    return system_certificate#012UnboundLocalError: local variable 'system_certificate' referenced before assignment```

Does anyone have an idea on how to fix this? It occurs when visiting the TLS SSL Page.

**Comment by Misentry** [comment]
Similar error here:

Traceback (most recent call last):
  File "/home/pasi/mailinabox/management/ssl_certificates.py", line 659, in <module>
    provision_certificates_cmdline()
  File "/home/pasi/mailinabox/management/ssl_certificates.py", line 371, in provision_certificates_cmdline
    status = provision_certificates(env, limit_domains=domains)
  File "/home/pasi/mailinabox/management/ssl_certificates.py", line 247, in provision_certificates
    domains, domains_cant_provision = get_certificates_to_provision(env, limit_domains=limit_domains)
  File "/home/pasi/mailinabox/management/ssl_certificates.py", line 228, in get_certificates_to_provision
    existing_cert = get_domain_ssl_files(domain, existing_certs, env, use_main_cert=False)
  File "/home/pasi/mailinabox/management/ssl_certificates.py", line 168, in get_domain_ssl_files
    return system_certificate
UnboundLocalError: local variable 'system_certificate' referenced before assignment

**Comment by JoshData** [comment]
Thanks. I think I fixed it on master in the commit above. Let me know if this works for you both?
