### ISSUE TITLE
Too many levels of symbolic links: '/home/user-data/ssl/ssl_certificate.pem'

### ISSUE THREAD

**Issue by nirtuj** [mail-in-a-box/mailinabox#1425]
After upgrading from 0.26 to the current  I ended up with a ssl_certificate.pem file that was a link pointing to itself & thus many services refused to run. I removed all files in the ssl folder and ran setup again and it was fine.

**Comment by thomae** [comment]
I encountered the same problem after upgrading from 0.27 to 0.28. My certificate is generated on a different server and then copied to
`/home/user-data/ssl/fullchain.pem` and
`/home/user-data/ssl/privkey.pem`. The symlinks therefore normally are
`/home/user-data/ssl/ssl_certificate.pem -> /home/user-data/ssl/fullchain.pem` and
`/home/user-data/ssl/ssl_private_key.pem -> /home/user-data/ssl/privkey.pem`.

Every night at 03:00 the `daily_tasks.sh` changes one of the symlinks to
`/home/user-data/ssl/ssl_certificate.pem -> /home/user-data/ssl/ssl_certificate.pem` and therefore all services associated with ssl stop working. I then need to manually reset the symlink to get back online:
```
sudo rm /home/user-data/ssl/ssl_certificate.pem
sudo ln -s /home/user-data/ssl/fullchain.pem /home/user-data/ssl/ssl_certificate.pem
sudo mailinabox
```

There is a [section](https://github.com/mail-in-a-box/mailinabox/blob/v0.28/management/ssl_certificates.py#L27) in `ssl_certificates.py` that should prevent this error but it seems not to be working. Any suggestions?

**Comment by teaborn2** [comment]
I'm in the same situation. I've got an error. The link updates in the night via cronjob in "/etc/cron.d/mailinabox-nightly". This script calls the script "ssl_certificates.py". But it fails with:
Sep 12 12:04:10 my-mailserver Exception on /ssl/provision [POST]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/root/mailinabox/management/daemon.py", line 53, in newview#012    return viewfunc(*args, **kwargs)#012  File "/root/mailinabox/management/daemon.py", line 383, in ssl_provision_certs#012    requests = provision_certificates(env, limit_domains=None)#012  File "/root/mailinabox/management/ssl_certificates.py", line 348, in provision_certificates#012    ret.extend(post_install_func(env))#012  File "/root/mailinabox/management/ssl_certificates.py", line 476, in post_install_func#012    ret.append( do_web_update(env) )#012  File "/root/mailinabox/management/web_update.py", line 78, in do_web_update#012    nginx_conf += make_domain_config(env['PRIMARY_HOSTNAME'], [template0, template1, template2], ssl_certificates, env)#012  File "/root/mailinabox/management/web_update.py", line 123, in make_domain_config#012    tls_cert = get_domain_ssl_files(domain, ssl_certificates, env)#012  File "/root/mailinabox/management/ssl_certificates.py", line 153, in get_domain_ssl_files#012    "certificate_object": load_pem(load_cert_chain(ssl_certificate)[0]),#012  File "/root/mailinabox/management/ssl_certificates.py", line 600, in load_cert_chain#012    with open(pemfile, "rb") as f:#012OSError: [Errno 40] Too many levels of symbolic links: '/home/user-data/ssl/ssl_certificate.pem'

All systemfiles have been updated to the latest version. mail-in-a-box is version 0.28.

Any help would be greatly appreciated. Because my letsencrypt certficate is only valid for 40 days.

Regards.

**Comment by ningappa** [comment]
same problem.

**Comment by ningappa** [comment]
happening for new installation too. 
can be easily reproduce while provisioning certificates button click.

**Comment by Dimantio** [comment]
Also having this issue.

**Comment by danielamor** [comment]
#1462 Got the same error, you can find the fix.

**Comment by gregmolnar** [comment]
I had this issue as well after an upgrade. I did the cleanup, then the setup script generated a self signed cert, and after that, I provisioned a letsencrypt one from the admin and it all seems to be back to normal.

**Comment by lobrien** [comment]
Is the defect at [Line 148](https://github.com/mail-in-a-box/mailinabox/blob/v0.28/management/ssl_certificates.py#LL148)? 

The symbolic link is created with the value of `cert['certificate']` [here](https://github.com/mail-in-a-box/mailinabox/blob/v0.28/management/ssl_certificates.py#LL461-LL461) and that, in turn, is set to `"ssl_certificate.pem"` at [448](https://github.com/mail-in-a-box/mailinabox/blob/v0.28/management/ssl_certificates.py#LL448).

448 calls `get_domain_ssl_files` without setting `allow_missing_cert`, which defaults to `False` at 144 and [145](https://github.com/mail-in-a-box/mailinabox/blob/v0.28/management/ssl_certificates.py#LL145) allows the clause to set `cert[certificate] = ssl_certificate.pem`.

**Comment by aarondemolder** [comment]
I'm also getting this issue, just moved a box from 14.04 to 18.04. (upgraded 0.30 > 0.44)

Admin panel became inaccessible overnight, rebooted, same issue, and then...

On running sudo mailinabox:

"failed to create symbolic link '/home/user-data/ssl/ssl_certificate.pem': File exists"

and on manually running management/ssl_certificates.py -

OSError: [Errno 40] Too many levels of symbolic links: '/home/user-data/ssl/ssl_certificate.pem'

The steps above from @danielamor fixed this, but I also hit my LetsEncrypt limit in the process, so looks like I'll have to wait a week to see results and just suck it up meanwhile with a self signed cert.
