### ISSUE TITLE
Sudden failure to renew LE cert

### ISSUE THREAD

**Issue by vectorselector** [mail-in-a-box/mailinabox#1426]
After a year of flawless service, our MIAB is suddenly not autorenewing LE certs.
Going to the admin ui via the IP and allowing a cert exception and clicking the PROVISION button does nothing but show the loading icon for about 2 seconds.
Meanwhile, the "certificate status" sections shows the box cert as:

"Certificate has a problem: The certificate has expired or is not yet valid. It is valid from 2018-06-01 09:01:36 to 2018-08-30 09:01:36. "

Which shows it as expired.

I've reinstalled MIAB. I've manually run the /root/mailinabox/ssl_certificates.py from bash.

What could this possibly be?

**Comment by rfrush** [comment]
What messages have you found in /var/log/letsencrypt/letsencrypt.log?

**Comment by vectorselector** [comment]
2018-08-30 14:31:31,646:DEBUG:certbot.main:Arguments: ['--non-interactive', '-d'
, 'box.ogreets.com', '--csr', '/tmp/tmpmtx_od7j', '--cert-path', '/tmp/tmple5k1a
4m/cert', '--chain-path', '/tmp/tmple5k1a4m/chain', '--fullchain-path', '/tmp/tm
ple5k1a4m/cert_and_chain.pem', '--webroot', '--webroot-path', '/home/user-data/s
sl/lets_encrypt/webroot', '--config-dir', '/home/user-data/ssl/lets_encrypt']
2018-08-30 14:31:31,646:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(P
luginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginE
ntryPoint#webroot)
2018-08-30 14:31:31,657:DEBUG:certbot.log:Root logging level set at 20
2018-08-30 14:31:31,658:INFO:certbot.log:Saving debug log to /var/log/letsencryp
t/letsencrypt.log
2018-08-30 14:31:31,659:DEBUG:certbot.plugins.selection:Requested authenticator 
webroot and installer None
2018-08-30 14:31:31,659:DEBUG:certbot.plugins.selection:Single candidate plugin:
 * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f9563ad5c88>
Prep: True
2018-08-30 14:31:31,660:DEBUG:certbot.plugins.selection:Selected authenticator <
certbot.plugins.webroot.Authenticator object at 0x7f9563ad5c88> and installer No
ne
2018-08-30 14:31:31,660:INFO:certbot.plugins.selection:Plugins selected: Authent
icator webroot, Installer None
2018-08-30 14:31:31,661:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 50, in get_
email
    force_interactive=True)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 529, in in
put
    self._interaction_fail(message, cli_flag)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 474, in _i
nteraction_fail
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry
 for this setting:
Enter email address (used for urgent renewal and security notices)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1238, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 641, in _init_le_c
lient
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 517, in _determine
_account
    config.email = display_ops.get_email()
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 54, in get_
email
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: You should register before running non-in
teractively, or provide --agree-tos and --email <email_address> flags.
2018-08-31 00:50:28,613:DEBUG:certbot.main:certbot version: 0.26.1
2018-08-31 00:50:28,614:DEBUG:certbot.main:Arguments: ['-q']
2018-08-31 00:50:28,614:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(P
luginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginE
ntryPoint#webroot)
2018-08-31 00:50:28,623:DEBUG:certbot.log:Root logging level set at 30
2018-08-31 00:50:28,624:INFO:certbot.log:Saving debug log to /var/log/letsencryp
t/letsencrypt.log
2018-08-31 00:50:28,633:DEBUG:certbot.plugins.selection:Requested authenticator 
<certbot.cli._Default object at 0x7f756e16ef98> and installer <certbot.cli._Defa
ult object at 0x7f756e16ef98>
2018-08-31 00:50:28,644:INFO:certbot.renewal:Cert not yet due for renewal
2018-08-31 00:50:28,645:DEBUG:certbot.plugins.selection:Requested authenticator 
standalone and installer None
2018-08-31 00:50:28,645:DEBUG:certbot.renewal:no renewal failures
2018-08-31 03:00:40,589:DEBUG:certbot.main:certbot version: 0.26.1
2018-08-31 03:00:40,590:DEBUG:certbot.main:Arguments: ['--non-interactive', '-d'
, 'box.ogreets.com', '--csr', '/tmp/tmp17y1i6n0', '--cert-path', '/tmp/tmpokokkp
7v/cert', '--chain-path', '/tmp/tmpokokkp7v/chain', '--fullchain-path', '/tmp/tm
pokokkp7v/cert_and_chain.pem', '--webroot', '--webroot-path', '/home/user-data/s
sl/lets_encrypt/webroot', '--config-dir', '/home/user-data/ssl/lets_encrypt']
2018-08-31 03:00:40,590:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(P
luginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginE
ntryPoint#webroot)
2018-08-31 03:00:40,602:DEBUG:certbot.log:Root logging level set at 20
2018-08-31 03:00:40,602:INFO:certbot.log:Saving debug log to /var/log/letsencryp
t/letsencrypt.log
2018-08-31 03:00:40,603:DEBUG:certbot.plugins.selection:Requested authenticator 
webroot and installer None
2018-08-31 03:00:40,604:DEBUG:certbot.plugins.selection:Single candidate plugin:
 * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7fe0f62dccc0>
Prep: True
2018-08-31 03:00:40,605:DEBUG:certbot.plugins.selection:Selected authenticator <
certbot.plugins.webroot.Authenticator object at 0x7fe0f62dccc0> and installer No
ne
2018-08-31 03:00:40,605:INFO:certbot.plugins.selection:Plugins selected: Authent
icator webroot, Installer None
2018-08-31 03:00:40,605:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 50, in get_
email
    force_interactive=True)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 529, in in
put
    self._interaction_fail(message, cli_flag)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 474, in _i
nteraction_fail
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry
 for this setting:
Enter email address (used for urgent renewal and security notices)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1238, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 641, in _init_le_c
lient
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 517, in _determine
_account
    config.email = display_ops.get_email()
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 54, in get_
email
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: You should register before running non-in
teractively, or provide --agree-tos and --email <email_address> flags.

**Comment by vectorselector** [comment]
I understand that it wants --agree-tos and --email me@mydomain.com  and i did provide those when running the /root/mailinabox/management/ssl_certificates.py as CLI options but still this error.

**Comment by vectorselector** [comment]
1) it worked flawlessly for 1 year + and then just suddenly failed to auto-renew

2) when i go to the MIAB server by IP address in the browser (insecure)   http://my-ip/admin
I click upon the "provision" button on the certificates tab of the app, and nothing happens. the same error message persists for the domain below:
`Certificate has a problem: The certificate has expired or is not yet valid. It is valid from 2018-06-01 09:01:36 to 2018-08-30 09:01:36`

3) manual attempts at running various combos of:
`/root/mailinabox/management/ssl_certificates.py --agree-tos --email me@mydomain.com` always fail with the error:
```
2018-09-01 03:12:01,718:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 50, in get_email
    force_interactive=True)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 529, in input
    self._interaction_fail(message, cli_flag)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 474, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Enter email address (used for urgent renewal and security notices)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1238, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 641, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 517, in _determine_account
    config.email = display_ops.get_email()
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 54, in get_email
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: You should register before running non-interactively, or provide --agree-tos and --email <email_address> flags.


```

**Comment by vectorselector** [comment]
FWIW, I freely provision LE certs on tons of subdomains every week, so it's not a LE problem, per se.

**Comment by vectorselector** [comment]
at the end, simply running "sudo mailinabox" and doing the setup over again (I had done this twice previously but via the `curl -s https://mailinabox.email/setup.sh | sudo bash ` method, not sure of the difference.

So, afterwards, I got one more error provisioning, then when i clicked the GUI button "provision" it finally did it, and all was good. I'll close this, as this method does solve it, but I can only guess as to the cause: (maybe that like the error says, you should register before running non-interactively and that some additional steps that i missed in the vast quantity of functionality present in https://github.com/mail-in-a-box/mailinabox/blob/master/management/ssl_certificates.py actually do this "registration" that I never deal with when simply running my usual "letsencrypt certonly --standalone -d sub.domain --email my@email.com --agree-tos on other systems)

like i said, it was impeccable in service until now, and there ARE a lot of moving parts, so i'll close it, but i'm still baffled a bit, not that it matters.

thank you. generally great product. appreciate the automatic creation of the extra records in terms of blocking the sub-domain sending by defaults etc.
