### ISSUE TITLE
CertBot Accept Terms Error

### ISSUE THREAD

**Issue by redflag237** [mail-in-a-box/mailinabox#1430]
[...]
Installing Munin (system monitoring)...
updated DNS: OpenDKIM configuration

-----------------------------------------------
Mail-in-a-Box uses Let's Encrypt to provision free certificates
to enable HTTPS connections to your box. You'll now be asked to agree
to Let's Encrypt's terms of service.

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Registering without email!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf. You must
agree in order to register with the ACME server at
https://acme-v02.api.letsencrypt.org/directory
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(A)gree/(C)ancel: (A)gree/(C)ancel: An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 721, in register
    _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 520, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 182, in register
    regr = perform_registration(acme, config, tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 207, in perform_registration
    tos_cb)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 777, in new_account_and_tos
    _assess_tos(self.client.directory.meta.terms_of_service)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 768, in _assess_tos
    check_tos_cb(tos)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 498, in _tos_cb
    cli_flag="--agree-tos", force_interactive=True)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 223, in yesno
    no=_parens_around_char(no_label)))
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 90, in input_with_timeout
    raise EOFError
EOFError
Please see the logfiles in /var/log/letsencrypt for more details.

-----------------------------------------------

Server runs fine, but the Certbot seems to have their interface changed. Does someone know how to fix that?

**Comment by redflag237** [comment]
This was due to an Update from v0.26c to v0.28. Server is Ubuntu 14.04.5 LTS.

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/mail-in-a-box/mailinabox/issues/1415
