### ISSUE TITLE
MIAB looses custom DNS entries randomly

### ISSUE THREAD

**Issue by tynie** [mail-in-a-box/mailinabox#1484]
Hi,

yesterday morning i noticed that all my custom DNS entries dissappeard. I then added all entries again and wanted to deal with the problem today. That happened between 1:41 - 2:30. Now I noticed this morning that all entries had disappeared again. 

At this time i noticed that these entries were visible in the syslog:
`box named[2880]: validating @0x7fb5f0045830: sbe.anydomainonmybox.de A: no valid signature found`

I suspect that the zone was then overwritten. After that not a single entry is visible anymore and all registered domains resolve to the IP of my mail in a box.
I think this has something to do with DNSSEC.

Does anyone have an idea what is going wrong?

**Comment by tynie** [comment]
This night it happened again. I think that must have something to do with the fact that I send DNS updates every 30 minutes from another server to MIAB. At 4:00:02 the zone files of 5 Domains were changed automatically.

syslog:

```
Dec 11 04:00:02 box nsd[13818]: signal received, shutting down...
Dec 11 04:00:02 box Exception on /dns/custom/user1.firstdyndnsdomain.de.de [PUT]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/_compat.py", line 35, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/home/config/mailinabox/management/daemon.py", line 53, in newview#012    return viewfunc(*args, **kwargs)#012  File "/home/config/mailinabox/management/daemon.py", line 315, in dns_set_record#012    return do_dns_update(env) or "Something isn't right."#012  File "/home/config/mailinabox/management/dns_update.py", line 86, in do_dns_update#012    sign_zone(domain, zonefile, env)#012  File "/home/config/mailinabox/management/dns_update.py", line 607, in sign_zone#012    dnssec_keys["KSK"] + ".key"#012  File "/home/config/mailinabox/management/utils.py", line 123, in shell#012    ret = getattr(subprocess, method)(cmd_args, **kwargs)#012  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output#012    raise CalledProcessError(retcode, process.args, output=output)#012subprocess.CalledProcessError: Command '['/usr/bin/ldns-key2ds', '-n', '-2', '/tmp/Kfirstdyndnsdomain.de.de.+007+30174.key']' returned non-zero exit status 1
Dec 11 04:00:02 box Exception on /dns/custom/user2.secondtdyndnsdomain.de.co [PUT]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/_compat.py", line 35, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/home/config/mailinabox/management/daemon.py", line 53, in newview#012    return viewfunc(*args, **kwargs)#012  File "/home/config/mailinabox/management/daemon.py", line 315, in dns_set_record#012    return do_dns_update(env) or "Something isn't right."#012  File "/home/config/mailinabox/management/dns_update.py", line 86, in do_dns_update#012    sign_zone(domain, zonefile, env)#012  File "/home/config/mailinabox/management/dns_update.py", line 607, in sign_zone#012    dnssec_keys["KSK"] + ".key"#012  File "/home/config/mailinabox/management/utils.py", line 123, in shell#012    ret = getattr(subprocess, method)(cmd_args, **kwargs)#012  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output#012    raise CalledProcessError(retcode, process.args, output=output)#012subprocess.CalledProcessError: Command '['/usr/bin/ldns-key2ds', '-n', '-1', '/tmp/Kfirstdyndnsdomain.de.de.+007+30174.key']' returned non-zero exit status 1
Dec 11 04:00:02 box named[1068]: received control channel command 'flush'
Dec 11 04:00:02 box named[1068]: flushing caches in all views succeeded
Dec 11 04:00:02 box nsd[16341]: nsd started (NSD 4.0.1), pid 16339
```

30 minutes later another zone file was changed.
syslog:

```
Dec 11 04:30:01 box CRON[19191]: (root) CMD (if [ -x /etc/munin/plugins/apt_all ]; then munin-run apt_all update 7200 12 >/dev/null; elif [ -x /etc/munin/plugins/apt ]; then munin-run apt update 7200 12 >/dev/null; fi)
Dec 11 04:30:01 box CRON[19192]: (munin) CMD (if [ -x /usr/bin/munin-cron ]; then /usr/bin/munin-cron; fi)
Dec 11 04:30:01 box named[1068]: received control channel command 'flush'
Dec 11 04:30:01 box named[1068]: flushing caches in all views succeeded
Dec 11 04:30:01 box nsd[19251]: nsd started (NSD 4.0.1), pid 19249
Dec 11 04:30:15 box postfix/smtpd[19686]: connect from mail-wm1-x32c.google.com[2a00:1450:4864:20::32c]
```

At 5:00 3 other zone files changed.
syslog

```
Dec 11 05:00:01 box CRON[22103]: (munin) CMD (if [ -x /usr/bin/munin-cron ]; then /usr/bin/munin-cron; fi)
Dec 11 05:00:02 box nsd[19251]: signal received, shutting down...
Dec 11 05:00:02 box Exception on /dns/custom/dynuser3.dyndnsdomain.com.co [PUT]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/_compat.py", line 35, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/home/config/mailinabox/management/daemon.py", line 53, in newview#012    return viewfunc(*args, **kwargs)#012  File "/home/config/mailinabox/management/daemon.py", line 315, in dns_set_record#012    return do_dns_update(env) or "Something isn't right."#012  File "/home/config/mailinabox/management/dns_update.py", line 86, in do_dns_update#012    sign_zone(domain, zonefile, env)#012  File "/home/config/mailinabox/management/dns_update.py", line 607, in sign_zone#012    dnssec_keys["KSK"] + ".key"#012  File "/home/config/mailinabox/management/utils.py", line 123, in shell#012    ret = getattr(subprocess, method)(cmd_args, **kwargs)#012  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output#012    raise CalledProcessError(retcode, process.args, output=output)#012subprocess.CalledProcessError: Command '['/usr/bin/ldns-key2ds', '-n', '-1', '/tmp/Kdyndnsdomain.com.co.+007+30174.key']' returned non-zero exit status 1
Dec 11 05:00:02 box Exception on /dns/custom/dynuser4.dyndnsdomain.com.co [PUT]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/_compat.py", line 35, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/home/config/mailinabox/management/daemon.py", line 53, in newview#012    return viewfunc(*args, **kwargs)#012  File "/home/config/mailinabox/management/daemon.py", line 315, in dns_set_record#012    return do_dns_update(env) or "Something isn't right."#012  File "/home/config/mailinabox/management/dns_update.py", line 86, in do_dns_update#012    sign_zone(domain, zonefile, env)#012  File "/home/config/mailinabox/management/dns_update.py", line 607, in sign_zone#012    dnssec_keys["KSK"] + ".key"#012  File "/home/config/mailinabox/management/utils.py", line 123, in shell#012    ret = getattr(subprocess, method)(cmd_args, **kwargs)#012  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output#012    raise CalledProcessError(retcode, process.args, output=output)#012subprocess.CalledProcessError: Command '['/usr/bin/ldns-key2ds', '-n', '-1', '/tmp/Kdyndnsdomain.com.co.+007+30174.key']' returned non-zero exit status 1
Dec 11 05:00:02 box named[1068]: received control channel command 'flush'
Dec 11 05:00:02 box named[1068]: flushing caches in all views succeeded
Dec 11 05:00:02 box nsd[22187]: nsd started (NSD 4.0.1), pid 22181
Dec 11 05:00:02 box nsd[22187]: signal received, shutting down...
Dec 11 05:00:02 box named[1068]: received control channel command 'flush'
Dec 11 05:00:02 box named[1068]: flushing caches in all views succeeded
Dec 11 05:00:02 box nsd[22226]: nsd started (NSD 4.0.1), pid 22224
```

**Comment by JoshData** [comment]
nsd zone files are re-written whenever DNS information needs to change. That's just how Mail-in-a-Box works. The only supported way to modify DNS records is to use the Custom DNS page of Mail-in-a-Box's control panel (/admin).

**Comment by JoshData** [comment]
Ah, sorry. Custom DNS entries are stored in `/home/user-data/dns/custom.yaml`. Can you take a look at what's happening with that file?

It sounds like the file is getting corrupted and is being reset. That _might_ happen if you have two things making an update at the exact same time.... although it's not supposed to happen.

**Comment by tynie** [comment]
I will have a look at that file next time.

Ok this makes sense but my cronjobs for updating the DNS entries run asynchronously to each other. So with one minute difference between each update.

Is it possible that updating the DNS records collides with the nightly backup?

**Comment by matDOTviguier** [comment]
I'm facing the same problem and do not want to open a new issue ...

**Comment by matDOTviguier** [comment]
Two times, cusom dns zone has been erased.
