### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by binarykitchen** [mail-in-a-box/mailinabox#1543]
From syslog

```
Mar 27 16:57:46 ec2-3-104-18-129 start[6677]: OSError: [Errno 40] Too many levels of symbolic links: '/home/user-data/ssl/ssl_certificate.pem'
Mar 27 16:57:46 ec2-3-104-18-129 Exception on /system/status [POST]#012multiprocessing.pool.RemoteTraceback: #012"""#012Traceback (most recent call last):#012  File "/usr/lib/python3.6
multiprocessing/pool.py", line 119, in worker#012    result = (True, func(*args, **kwds))#012  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar#012    return
ist(itertools.starmap(args[0], args[1]))#012  File "/home/michael-heuberger/mailinabox/management/status_checks.py", line 343, in run_domain_checks_on_domain#012    check_primary_hostn
me_dns(domain, env, output, dns_domains, dns_zonefiles)#012  File "/home/michael-heuberger/mailinabox/management/status_checks.py", line 420, in check_primary_hostname_dns#012    tlsa2
_expected = build_tlsa_record(env)#012  File "/home/michael-heuberger/mailinabox/management/dns_update.py", line 322, in build_tlsa_record#012    cert = load_pem(load_cert_chain(fn)[0]
#012  File "/home/michael-heuberger/mailinabox/management/ssl_certificates.py", line 600, in load_cert_chain#012    with open(pemfile, "rb") as f:#012OSError: [Errno 40] Too many level
 of symbolic links: '/home/user-data/ssl/ssl_certificate.pem'#012"""#012#012The above exception was the direct cause of the following exception:#012#012Traceback (most recent call last
:#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/ma
linabox/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python
.6/site-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/_
ompat.py", line 35, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = se
f.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint]
**req.view_args)#012  File "/home/michael-heuberger/mailinabox/management/daemon.py", line 53, in newview#012    return viewfunc(*args, **kwargs)#012  File "/home/michael-heuberger/mai
inabox/management/daemon.py", line 441, in system_status#012    run_checks(False, env, output, pool)#012  File "/home/michael-heuberger/mailinabox/management/status_checks.py", line 64
 in run_checks#012    run_domain_checks(rounded_values, env, output, pool)#012  File "/home/michael-heuberger/mailinabox/management/status_checks.py", line 322, in run_domain_checks#01
    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)#012  File "/usr/lib/python3.6/multiprocessing/pool.py", line 296, in starmap#012    return self._map_async(func,
terable, starmapstar, chunksize).get()#012  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get#012    raise self._value#012OSError: [Errno 40] Too many levels of symbo
ic links: '/home/user-data/ssl/ssl_certificate.pem'
```

**Comment by binarykitchen** [comment]
I've ran sudo mailinabox few times in a row. Maybe this made a mess with symbolic links? Duno know ...

**Comment by jvolkenant** [comment]
Might be the same as #1425

**Comment by binarykitchen** [comment]
yup, it's the same
