### ISSUE TITLE
Waiting for mail in a box management daemon to start

### ISSUE THREAD

**Issue by TrooperAustin** [mail-in-a-box/mailinabox#1691]
I am in the process of installing mail in a box and have gotten stuck at this point several times, I have tried to reinstall, and it has done nothing, heres the log:

Installing add-apt-repository...
Updating system packages...
Installing system packages...

Current default time zone: 'US/Eastern'
Local time is now:      Wed Dec  4 15:49:49 EST 2019.
Universal Time is now:  Wed Dec  4 20:49:49 UTC 2019.

Initializing system random number generator...
Creating SSH key for backup…
Firewall is active and enabled on system startup
Creating initial SSL certificate and perfect forward secrecy Diffie-Hellman parameters...
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
..................+..+...........................................................................+...............+...................+..............+.......................................................................................+......+.......+..........+.....................................................................................................................+......................................................................................................................................................................................................................................................................................................................................................................................................+.........+....+.......................................................+.....................................................................+....................................................................+.......................................+.....................................................................................................................................+.......................................................................+..........................................................................................................................................+................................................................................................................................................+........................................................+.............................................+....................................................................+........................................+.......................................................+..........................................................................................................+...................................................................................+...................+.........................................................................................................................................................+.................................................................................................................................+.............................................................................................+.....................................................................................................+.......................................................+...+.........................................................................................+......................................................................................................................................................+..............................+......................................+....+.........................+......+...+.................+.................+....................................................................................................................................................................................................................................+.........................................................................................................................+............................................................................................................................................................................................................+..................................................................................................................+......................................................................+..............................+.............................................................................................................................................................+....+............................................................................................................................+.............+...............................................................................................+..................+.............................+.............................................................+..........+.......................................................+................+..............................................+.............................+..........................+......................................+..................+..............................................+................................................................................................................................................+......................................+..............................................+.................................................+.........................+.................+...........+.................+.............+...............+...............................+........................................................................................................................................................+.....................................+..................................................................................................................................................................................................................................+.........................................................+...................................................................................................................................+......................................................+.................................................+.....................................+...........................................................................................................................+............................................................................................................................................................+..............................................................................................................................................+........................................+...................+..........................................................................................................................................................................................................................................................................+.................................................................................................................................................................+..............................................................................................................................................................................................................................................+......................................................................+................................................................................................................................................+...........................................................................................+...............................................................................................................................................................................................................................................................................................................+.....................................+...............................................................................................................+....................................+.................................+...........................................................................................+..........+.....+...............................................................................+..................................................................................................................................................................................................................................+............................+....................................+.........................................................................................................+................+.............................................................+.............................................+.....................................+..............+....................................................................................................+..............................................................................................+..................................................................+..................................................................................................................................................................................................................+...........................................................+............................................................................................................................................................+...................................+........+..........................................................................................................................+...................................................................+...........................+..........................................................................................................................................+........................................................................................................+...........+....................................+.......................................................................+........................................................................................................+..........................................+.+........................................................................................+........................................................................................................................................................................................+...........................................................+..................................+...........+...........................................................................................................................+............................................................................................................+............................................................+...................................................................+.............+...............................................................................................+.....................................................................................................................................................................................................................+.........................................................+...............................................+.........+.........................+.......................................+..............................................................................................................................................................................................................................................+.................................................................................................................................................................................................+......................................................................................+......................................................................+................................+..............+..................................................................+..........................................................................................................+..............................................+.............................................................................................................................................+....................................................................................................................+..............................................................................................................................................+..............................+..................................................................................+......+.........................+.....................................................................................................+............................................................................................................................................................+.............................................................+.+......+..............................................................................................+...........................................................................................+...................................................................................................................................+.........................................................................................................................................................................................................................................+..........+........................+..+.........................................+.....................................................................................................................................................................................................................................................................................................................................................................................................+...............................................................................................................................................................................................................................................................................................+...............................+.....................................................................................................+.......................................................................................................................................................................................+.............................................................................................................................+.........+..............................................................................................................+............................................................................................................................................................................................................+.......................................................................+........................................................................................................................................................................+...............................................................................................................+.................................................................+....................................................+..............+...........................................................................................................................................................................................................................................................................+.....+.....................................................................................................................................................................................................................+..........................................+........+...........................................................................................................................................................................................................+........................................................................................................................................................................................................+...........+.......................................................................................+..............+........................................+..................................................................................................................................................................................................................................................+.............................................................+............................................................................................................................................................................+.............................................................................................................................+.............................................................................................................................................................................................................................................+....................................................+............+...............................................................................................................................................................................+........................................................................................................................................+............+...........................+.........................+........................................................................................................................................................................................................+................................................................................................+.+................+...................................................................+........................................................................................................................................................................................................................+...............................................................................................................................................+....................+.........................................................................................................................................................................................................................................................................................................+....................................................................................+....................................+....+.....................................................................................................................................+............................................................................................................................................................................+............................................................................................................................................+.............................................................................................................................................................+....................................................................+.................................................................................................................+..............................................................................+................................................................................................................................................................+....................................+..................................................................................................+............................................................................................................................................................................................................................................+......................................+............................................+.............................................................................................+.................+...........................................................................+......................+...............+......+..................................................+.............................................................................................................................................................................................+...................+.................................+....................................................................................................................++*++*++*++*
Installing nsd (DNS server)...
Generating DNSSEC signing keys...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Creating new user database: /home/user-data/mail/users.sqlite
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...

Upgrading to Nextcloud version 15.0.8

Nextcloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
goes on for another 1000 lines..

**Comment by just4t** [comment]
Confirm you VPS server provider you attempted to install it ... upcloud, perhaps?

**Comment by TrooperAustin** [comment]
Zap-Hosting

**Comment by just4t** [comment]
As far as Iknow that happened to me with upcloud in the past and the reason was that _locale_ were not already installed/ set in their `rpvided default ubuntu 18.04 image ... Check if locale is already correctly set before to try to install Mail-in-a-Box and report final results here at your end. This article could be of help:  https://lintut.com/how-to-set-up-system-locale-on-ubuntu-18-04/

**Comment by TrooperAustin** [comment]
Ill try that when i get home, will keep you posted

**Comment by just4t** [comment]
BTW, Seeing  **Zap-Hosting** provides **LXC based Linux VPS** for linux servers instead than KVM (KVM is the one offered by the most known major providers like DigitalOcean, Vultr, Upcloud, Linode, Exoscale ... ) you may need to check its compatibility, too (I can't help on that as I didn't use LXC based servers).

**Comment by TrooperAustin** [comment]
Okay, this is just a test server (they are only $1.50 for 7 days). So if it doesnt work ill move to my more permanent solution

**Comment by jvolkenant** [comment]
https://github.com/mail-in-a-box/mailinabox/blob/ccd153065b74debf87a1dd63747d96d00d6931bd/setup/start.sh#L114-L119

It cannot connect to localhost port 10222. Can you ssh into your host in another terminal session and investigate?  

What does `service mailinabox status` report?

**Comment by TrooperAustin** [comment]
What commands should i run?

**Comment by guyzmo** [comment]
I just ran into that issue, what caused this is a failure to launch mailinabox. Instead of an infinite loop, what would be a good idea would be to check `systemctl mailinabox status` and output whether it failed, and if it did show the error, and tell how to move on with the installation/upgrade.

I actually fixed the issue in another terminal, and did a `systemctl mailinabox start` which worked and it went on with the installation.

**Comment by theiosdevguy** [comment]
Hello Team,

I am facing the same issue and the status command message is as below

```
* mailinabox.service - Mail-in-a-Box System Management Service
   Loaded: loaded (/lib/systemd/system/mailinabox.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-11-30 11:16:10 IST; 2s ago
  Process: 8357 ExecStart=/usr/local/lib/mailinabox/start (code=exited, status=1/FAILURE)
 Main PID: 8357 (code=exited, status=1/FAILURE)

Nov 30 11:16:10 box.nebula.codes systemd[1]: Started Mail-in-a-Box System Management Service.
Nov 30 11:16:10 box.nebula.codes start[8357]: Traceback (most recent call last):
Nov 30 11:16:10 box.nebula.codes start[8357]:   File "/root/mailinabox/management/daemon.py", line 28, in <module>
Nov 30 11:16:10 box.nebula.codes start[8357]:     for line in f:
Nov 30 11:16:10 box.nebula.codes start[8357]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/encodings/ascii.py", line 26, in decode
Nov 30 11:16:10 box.nebula.codes start[8357]:     return codecs.ascii_decode(input, self.errors)[0]
Nov 30 11:16:10 box.nebula.codes start[8357]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 795: ordinal not in ran
Nov 30 11:16:10 box.nebula.codes systemd[1]: mailinabox.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 11:16:10 box.nebula.codes systemd[1]: mailinabox.service: Failed with result 'exit-code'.
```

Please suggest

**Comment by tydoo** [comment]
Hello,

Yes, i have the same problem :

`root@mail:~# systemctl status mailinabox
* mailinabox.service - Mail-in-a-Box System Management Service
   Loaded: loaded (/lib/systemd/system/mailinabox.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-12-02 02:18:46 CET; 5min ago
 Main PID: 43664 (code=exited, status=1/FAILURE)

Dec 02 02:18:45 mail.ecowan.network systemd[1]: Started Mail-in-a-Box System Management Service.
Dec 02 02:18:46 mail.ecowan.network start[43664]: Traceback (most recent call last):
Dec 02 02:18:46 mail.ecowan.network start[43664]:   File "/root/mailinabox/management/daemon.py", line 28, in <module>
Dec 02 02:18:46 mail.ecowan.network start[43664]:     for line in f:
Dec 02 02:18:46 mail.ecowan.network start[43664]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/encodings/ascii.py", line 26, in dec
Dec 02 02:18:46 mail.ecowan.network start[43664]:     return codecs.ascii_decode(input, self.errors)[0]
Dec 02 02:18:46 mail.ecowan.network start[43664]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 795: ordinal not in
Dec 02 02:18:46 mail.ecowan.network systemd[1]: mailinabox.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 02:18:46 mail.ecowan.network systemd[1]: mailinabox.service: Failed with result 'exit-code'.
lines 1-14/14 (END)
`
