### ISSUE TITLE
Problem installing on Ubuntu 18.04.2 LTS bash script FAILED: pip3 install email_validator>=1.0.0

### ISSUE THREAD

**Issue by XcomReborn** [mail-in-a-box/mailinabox#1727]
I'm trying to run the bash setup script for the first time:

curl -s https://mailinabox.email/setup.sh | sudo bash

And I get this output:

FAILED: pip3 install email_validator>=1.0.0
-----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pip 20.0.2 (/home/xcomreborn/.local/lib/python3.6/site-packages), Requirement.parse('pip==1.5.6'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==1.5.6' distribution was not found and is required by the application
-----------------------------------------

I've tried purging pip3 and reinstalling it, and updating python but no idea whats happening. I think this is a problem with pip3 because running pip3 --version throws similar errors but I don't know how to rectify it.

**Comment by XcomReborn** [comment]
ok I eventually solved this by manually locating the pip3 directories using:

whereis pip3

then manually removing all of them (there were four directories) using eg:

sudo rm -rf /usr/bin/pip3  ..... for each directory

I then used :

sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

to get a new setup file for pip3 and ran it using:

sudo python3 get-pip.py

I followed the steps from Iwairore : https://stackoverflow.com/questions/43847317/cant-remove-python-pip

This was a pip3 problem as suspected.
