### ISSUE TITLE
S3 backups failing

### ISSUE THREAD

**Issue by tylerapplebaum** [mail-in-a-box/mailinabox#1851]
Getting a broken pipe error on the automated (and manual) attempts to back up to S3. CloudTrail shows no activity for my API calls, so the connection doesn't appear to even be made to the S3 bucket.

```
ubuntu@mail01:~/mailinabox/management$ sudo ./backup.py
Attempt 1 failed. error: [Errno 32] Broken pipe
Attempt 2 failed. error: [Errno 32] Broken pipe
Attempt 3 failed. error: [Errno 32] Broken pipe
Attempt 4 failed. error: [Errno 32] Broken pipe
Giving up after 5 attempts. error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "./backup.py", line 561, in <module>
    perform_backup(full_backup)
  File "./backup.py", line 279, in perform_backup
    get_env(env))
  File "/home/ubuntu/mailinabox/management/utils.py", line 123, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/duplicity', 'full', '--verbosity', 'warning', '--no-print-statistics', '--archive-dir', '/home/user-data/backup/cache', '--exclude', '/home/user-data/backup', '--volsize', '250', '--gpg-options', '--cipher-algo=AES256', '/home/user-data', 's3://s3.us-east-2.amazonaws.com/<my-bucket-name>/mail-backup', '--allow-source-mismatch', '--ssh-options= -i /root/.ssh/id_rsa_miab', '--rsync-options= -e "/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 22 -i /root/.ssh/id_rsa_miab"']' returned non-zero exit status 50.
```

**Comment by tylerapplebaum** [comment]
Did indeed turn out to be a permissions issue. I believe Duplicity is using s3cmd to move the data to S3, and s3cmd has notoriously crappy error messages.

Here's the IAM policy that should be attached your user to allow for S3 backups.

[This blog post](https://www.jeremyshapiro.com/2011/02/errno-32-broken-pipe-in-s3cmd/) and comment section have more info on s3cmd and what `[Errno 32] Broken Pipe` means.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:GetBucketAcl",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::<your-bucket-here>/*",
                "arn:aws:s3:::<your-bucket-here>"
            ]
        }
    ]
}
```
