### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by plittlefield** [mail-in-a-box/mailinabox#1897]
I am getting this error on the weekly log report...

```
Subject: Status Checks Change Notice
 
System -- Previously:
=====================
Traceback (most recent call last):
  File "management/status_checks.py", line 1031, in <module>
    run_and_output_changes(env, pool)
  File "management/status_checks.py", line 917, in run_and_output_changes
    BufferedOutput(with_lines=prev_lines[i1:i2]).playback(out)
  File "management/status_checks.py", line 1017, in playback
    getattr(output, attr)(*args, **kwargs)
  File "management/status_checks.py", line 960, in print_error
    self.print_block(message, first_line="\u2716  ")
  File "management/status_checks.py", line 966, in print_block
    print(first_line, end='', file=self.buf)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2716' in position 0: ordinal not in range(128)
```

Any ideas?

Paully

**Comment by brownj** [comment]
I ran into a similar issue.

I think the issue is that your not using the UTF-8 locale for your server. And the status checks return the UTF-8 characters for the checkmark or X that you see on the status webpage. e.g., 
> System
> ======
> ✓  All system services are running.
> ✖  MTA-STS policy is missing: STSFetchResult.NONE

I fixed this by updating the locale for my server. On my server, I ran `dpkg-reconfigure locales` and then switched the default locale from en_US to en_US.UTF-8.

Since it appears as though you're in the UK, you'd probably want to choose en_UK-UTF-8, I expect, for your locale for your server.
