### ISSUE TITLE
Incorrect interpretation of Backblaze B2 MD5 checksums

### ISSUE THREAD

**Issue by eableson** [mail-in-a-box/mailinabox#1922]
It appears that the B2 API returns the checksum values with a prefix and in quotation marks, which results in the following errors in the backup validation process:

```
Attempt 1 failed. S3DataError: ETag from S3 did not match computed MD5. 819741d846d4d5d9cb680df0b84903f4 vs. b'819741d846d4d5d9cb680df0b84903f4'
Attempt 2 failed. S3DataError: ETag from S3 did not match computed MD5. 819741d846d4d5d9cb680df0b84903f4 vs. b'819741d846d4d5d9cb680df0b84903f4'
Attempt 3 failed. S3DataError: ETag from S3 did not match computed MD5. 819741d846d4d5d9cb680df0b84903f4 vs. b'819741d846d4d5d9cb680df0b84903f4'
Attempt 4 failed. S3DataError: ETag from S3 did not match computed MD5. 819741d846d4d5d9cb680df0b84903f4 vs. b'819741d846d4d5d9cb680df0b84903f4'
Giving up after 5 attempts. S3DataError: ETag from S3 did not match computed MD5. 819741d846d4d5d9cb680df0b84903f4 vs. b'819741d846d4d5d9cb680df0b84903f4'
Traceback (most recent call last):
  File "management/backup.py", line 578, in <module>
    perform_backup(full_backup)
  File "management/backup.py", line 279, in perform_backup
    get_env(env))
  File "/home/cubeadmin/mailinabox/management/utils.py", line 123, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/duplicity', 'full', '--verbosity', 'warning', '--no-print-statistics', '--archive-dir', '/home/user-data/backup/cache', '--exclude', '/home/user-data/backup', '--volsize', '250', '--gpg-options', '--cipher-algo=AES256', '/home/user-data', 's3://s3.eu-central-003.backblazeb2.com/mailinabox-office/backups', '--allow-source-mismatch', '--ssh-options= -i /root/.ssh/id_rsa_miab', '--rsync-options= -e "/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 22 -i /root/.ssh/id_rsa_miab"']' returned non-zero exit status 50.
```

The checksum values are the same, but it looks like the return codes are wrapped with additional characters. Not sure if this variation is considered acceptable by the standard S3 API, but it appears to be easily treatable by checking for quotes and using the contents inside for the comparison.

**Comment by fspoettel** [comment]
as far as I know, B2's S3-compatible API is not 100% compatible with Duplicity yet. At least it wasn't the last time I tried to use it. We use Duplicity for performing / validating backups and have no control over its internals.

B2 support was implemented recently via https://github.com/mail-in-a-box/mailinabox/pull/1812 but had to be reverted for now (see https://github.com/mail-in-a-box/mailinabox/commit/b1d703a5e717c086aea0e37e9b14f78150181880). Would having a b2 option for backups address your issue?

**Comment by eableson** [comment]
Effectively a direct B2 option would solve the problem (which obviates the need for the Duplicity/B2 integration to be worked out)
