### ISSUE TITLE
0.52 doe not show content of backup 

### ISSUE THREAD

**Issue by aroundmyroom** [mail-in-a-box/mailinabox#1923]
When trying to access the backup page I see that version 0.52 is unable to retrieve and show the content of the remote folder when its rsync

Something went wrong, sorry. is what I get

I have checked the backup.py and it does not matter if V.051 or V.052 is being used, both backup.py's do not work
so I think something is reported through the API cause I know for sure that data is taken / read from the remote rsync location
.backup.py is working

the only issue I see at the end is

Using temporary directory /tmp/duplicity-awjobq8q-tempdir
Traceback (most recent call last):
  File "./backup.py", line 543, in <module>
    run_duplicity_verification()
  File "./backup.py", line 354, in run_duplicity_verification
    ] + rsync_ssh_options, get_env(env))
  File "/root/mailinabox/management/utils.py", line 123, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/duplicity', '--verbosity', 'info', 'verify', '--compare-data', '--archive-dir', '/home/user-data/backup/cache', '--exclude', '/home/user-data/backup', 'rsync://aa@bb.cc.org//srv/Backups/Backup_Mail', '/home/user-data', '--rsync-options=-e "/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 22 -i /root/.ssh/id_rsa_miab"']' 
returned non-zero exit status 23.

**Comment by aroundmyroom** [comment]
reboot machine solved the issue ..
