### ISSUE TITLE
Install error with email_validator version 1.1.2 and python 3.4 in ubuunt 14

### ISSUE THREAD

**Issue by syscon3** [mail-in-a-box/mailinabox#1959]
The setup fail when validate email address...
I Fix it installing email_validator 1.1.0.

My system:
ubuntu 14.04 (x86_64)
Python 3.4.3

Error:
Traceback (most recent call last):
  File "emailvalid.py", line 1, in <module>
    from email_validator import validate_email, EmailNotValidError
  File "/usr/local/lib/python3.4/dist-packages/email_validator/__init__.py", line 6, in <module>
    import dns.resolver
  File "/usr/local/lib/python3.4/dist-packages/dns/resolver.py", line 32, in <module>
    import dns.flags
  File "/usr/local/lib/python3.4/dist-packages/dns/flags.py", line 24, in <module>
    class Flag(enum.IntFlag):
AttributeError: 'module' object has no attribute 'IntFlag'

**Comment by myfirstnameispaul** [comment]
Please note that the project has migrated to Ubuntu 18.04 and is no longer supporting Ubuntu 14.04.

Please see [Upgrading Mail-in-a-Box](https://mailinabox.email/maintenance.html#upgrade) for more information.
