### ISSUE TITLE
Upgrade to v0.53 cannot access Custom DNS

### ISSUE THREAD

**Issue by slave2anubis** [mail-in-a-box/mailinabox#1961]
Hello everybody. Just did the 0.53 update and now i cannot access the Custom DNS page.
![Screenshot_2021-04-13 box isupply ro - Mail-in-a-Box Control Panel](https://user-images.githubusercontent.com/6576904/114550525-fa9d2080-9c6a-11eb-8841-cddc2a623813.png)

Logs:
`pr 13 15:05:43 box start[1447]: 127.0.0.1 - - [13/Apr/2021 15:05:43] "POST /system/status HTTP/1.0" 200 -
Apr 13 15:05:47 box start[1447]: 127.0.0.1 - - [13/Apr/2021 15:05:47] "GET /dns/secondary-nameserver?_=1618315536213 HTTP/1.0" 200 -
Apr 13 15:05:47 box start[1447]: 127.0.0.1 - - [13/Apr/2021 15:05:47] "GET /dns/zones?_=1618315536214 HTTP/1.0" 200 -
Apr 13 15:05:47 box start[1447]: [2021-04-13 15:05:47,072] ERROR in app: Exception on /dns/custom [GET]
Apr 13 15:05:47 box start[1447]: Traceback (most recent call last):
Apr 13 15:05:47 box start[1447]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
Apr 13 15:05:47 box start[1447]:     response = self.full_dispatch_request()
Apr 13 15:05:47 box start[1447]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 13 15:05:47 box start[1447]:     rv = self.handle_user_exception(e)
Apr 13 15:05:47 box start[1447]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
Apr 13 15:05:47 box start[1447]:     reraise(exc_type, exc_value, tb)
Apr 13 15:05:47 box start[1447]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
Apr 13 15:05:47 box start[1447]:     raise value
Apr 13 15:05:47 box start[1447]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 13 15:05:47 box start[1447]:     rv = self.dispatch_request()
Apr 13 15:05:47 box start[1447]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
Apr 13 15:05:47 box start[1447]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 13 15:05:47 box start[1447]:   File "/home/ubuntu/mailinabox/management/daemon.py", line 70, in newview
Apr 13 15:05:47 box start[1447]:     return viewfunc(*args, **kwargs)
Apr 13 15:05:47 box start[1447]:   File "/home/ubuntu/mailinabox/management/daemon.py", line 316, in dns_get_records
Apr 13 15:05:47 box start[1447]:     for i, r in enumerate(sorted(records, key = lambda r : (
Apr 13 15:05:47 box start[1447]:   File "/home/ubuntu/mailinabox/management/daemon.py", line 317, in <lambda>
Apr 13 15:05:47 box start[1447]:     zones.index(r["zone"]),
Apr 13 15:05:47 box start[1447]: KeyError: 'zone'
Apr 13 15:05:47 box Exception on /dns/custom [GET]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/home/ubuntu/mailinabox/management/daemon.py", line 70, in newview#012    return viewfunc(*args, **kwargs)#012  File "/home/ubuntu/mailinabox/management/daemon.py", line 316, in dns_get_records#012    for i, r in enumerate(sorted(records, key = lambda r : (#012  File "/home/ubuntu/mailinabox/management/daemon.py", line 317, in <lambda>#012    zones.index(r["zone"]),#012KeyError: 'zone'
Apr 13 15:05:47 box start[1447]: 127.0.0.1 - - [13/Apr/2021 15:05:47] "GET /dns/custom?_=1618315536215 HTTP/1.0" 500 -
Apr 13 15:07:27 box postfix/smtpd[2994]: connect from starttls-virginia.proxy-research.com[34.227.19.103]
Apr 13 15:07:28 box postfix/smtpd[2994]: disconnect from starttls-virginia.proxy-research.com[34.227.19.103] ehlo=2 starttls=1 quit=1 commands=4
Apr 13 15:09:01 box CRON[3004]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Apr 13 15:09:07 box systemd[1]: Starting Clean php session files...
Apr 13 15:09:07 box systemd[1]: Started Clean php session files.`

**Comment by myfirstnameispaul** [comment]
Is it possible to edit your issue by pasting the logs in with one log entry per line, highlight the logs lines all at once, then click the  'Insert a quote' button in the toolbar?

**Comment by mveplus** [comment]
I have just updated to v.0.53 and can confirm this issue as well.

It looks like it has something to do with the change @JoshData  did in [6653dbb](https://github.com/mail-in-a-box/mailinabox/commit/6653dbb2e2357462d22685a06f688f1fb02ed3cd)  for [custom DNS request](https://github.com/mail-in-a-box/mailinabox/issues/1927)  in management/daemon.py. 

As the error suggests in the system logs: 

> File "/root/mailinabox/management/daemon.py", line 316, in dns_get_records#012    for i, r in enumerate(sorted(records, key = lambda r : (#012  File "/root/mailinabox/management/daemon.py", line 317, in <lambda>#012    zones.index(r["zone"]),#012KeyError: 'zone'

But I'm not fluent in Python and not familiar with the admin app but this looks like the[ relevant code](https://github.com/mail-in-a-box/mailinabox/commit/6653dbb2e2357462d22685a06f688f1fb02ed3cd) line 316 and 317.

The [custom DNS request](https://github.com/mail-in-a-box/mailinabox/issues/1927) is a great idea though! 

Cheers,

**Comment by fkieber** [comment]
Hi.
After comparing a new yaml file with the old one, I have found that there was an old domain name.
This domain name was used previously, but I have it recently migrated somewhere and forgotten to remove it in custom DNS.
Removing all its entry by hand in custom.yaml file do the job.

**Comment by FlorianMiesenberger** [comment]
Hi, 

in our organization we are also using the custom DNS feature a lot... and by that I really mean A LOT... our custom.yaml file has 328 lines :-D and we where also using version 0.53 but now we went back because we had the same problem: 
<img width="936" alt="grafik" src="https://user-images.githubusercontent.com/6874610/115405096-3a758200-a1ee-11eb-9aed-b83d03912eab.png">

The logs seem to be also the same (sorry for very bad formating! The newlines are gone in this paste): 
`Apr 20 12:09:27 hostname Exception on /dns/custom [GET]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise#012    raise value#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/home/ubuntu/mailinabox/management/daemon.py", line 70, in newview#012    return viewfunc(*args, **kwargs)#012  File "/home/ubuntu/mailinabox/management/daemon.py", line 316, in dns_get_records#012    for i, r in enumerate(sorted(records, key = lambda r : (#012  File "/home/ubuntu/mailinabox/management/daemon.py", line 317, in <lambda>#012    zones.index(r["zone"]),#012KeyError: 'zone'
`

I didn't saved a snapshot of this virtual machine, but I'm sure I am able to reproduce this error again, if you tough developers need some more logs or something. I don't have any developer skills to easy help you fixing this problem, but I'm trying to assist you. 

Thanks you for your awesome work! Our benefits because of using this project are huge and we don't even assist the community. Because of that I'm trying to at least give you some more details about this. And for us it's not a hurry to fix this, beacause v0.52 is working just fine. 

Greetz from Austria!

**Comment by fkieber** [comment]
Hi  FlorianMiesenberger,

Have you verify if you have domains in custom DNS that are not in users ?
If so, remove they and give 0.53 a new try.

**Comment by slave2anubis** [comment]
I can 

> Hi,
> 
> in our organization we are also using the custom DNS feature a lot... and by that I really mean A LOT... our custom.yaml file has 328 lines :-D and we where also using version 0.53 but now we went back because we had the same problem:
> <img alt="grafik" width="936" src="https://user-images.githubusercontent.com/6874610/115405096-3a758200-a1ee-11eb-9aed-b83d03912eab.png">
> 
> The logs seem to be also the same (sorry for very bad formating! The newlines are gone in this paste):
> `Apr 20 12:09:27 hostname Exception on /dns/custom [GET]#012Traceback (most recent call last):#012 File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app#012 response = self.full_dispatch_request()#012 File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request#012 rv = self.handle_user_exception(e)#012 File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception#012 reraise(exc_type, exc_value, tb)#012 File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise#012 raise value#012 File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request#012 rv = self.dispatch_request()#012 File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request#012 return self.view_functions[rule.endpoint](**req.view_args)#012 File "/home/ubuntu/mailinabox/management/daemon.py", line 70, in newview#012 return viewfunc(*args, **kwargs)#012 File "/home/ubuntu/mailinabox/management/daemon.py", line 316, in dns_get_records#012 for i, r in enumerate(sorted(records, key = lambda r : (#012 File "/home/ubuntu/mailinabox/management/daemon.py", line 317, in <lambda>#012 zones.index(r["zone"]),#012KeyError: 'zone' `
> 
> I didn't saved a snapshot of this virtual machine, but I'm sure I am able to reproduce this error again, if you tough developers need some more logs or something. I don't have any developer skills to easy help you fixing this problem, but I'm trying to assist you.
> 
> Thanks you for your awesome work! Our benefits because of using this project are huge and we don't even assist the community. Because of that I'm trying to at least give you some more details about this. And for us it's not a hurry to fix this, because v0.52 is working just fine.
> 
> Greetz from Austria!

Hello Florian,
I can confirm that the solution @fkieber  offered works. 
You need to open the following fine:
`sudo nano /users/user-data/dns/custom.yaml`
Then search and delete every unused domain that does not have a valid email address on your server. 

If you still need help, i can look into the issue for you. Send me a message.

**Comment by mveplus** [comment]
@slave2anubis
Beautiful! That works, I was not even noticed that a few of my old and unused domains are still kept somewhere ;) 

Deleting the lines below in the /home/user-data/dns/custom.yaml solved the issue! 
 
```
*.old_domain.com : 
      CNAME: old_domain.com.
```
and

```
old_domain.com : 
    TXT:  google-site-verification="code" 
```

Thanks for the tip!

**Comment by JMSwag** [comment]
Removing unused domains from "/home/user-data/dns/custom.yaml" then running ```./mailinabox/tools/dns_update --force``` resolved the issue for me.
