### ISSUE TITLE
connection refused to letsencrypt

### ISSUE THREAD

**Issue by bellaj** [mail-in-a-box/mailinabox#1972]
I am installing mailinabox on a VPS (ubuntu 18) and I've got this error : 

>Mail-in-a-Box uses Let's Encrypt to provision free SSL/TLS certificates
to enable HTTPS connections to your box. We're automatically
agreeing you to their subscriber agreement. See https://letsencrypt.org.

>Saving debug log to /var/log/letsencrypt/letsencrypt.log
Registering without email!
An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Any suggestions?

**Comment by bellaj** [comment]
I've managed to solve this issue by using :

>certbot certonly -a webroot -w /var/www/html -d example.org -d www.example.org

then relaunch the installation
