### ISSUE TITLE
A Cautionary Tale on do-release-upgrade

### ISSUE THREAD

**Issue by stvhay** [mail-in-a-box/mailinabox#2161]
So I decided to try, on a computer that i didn't have anything i wanted to keep on it, to upgrade from 18.04 to 22.04 with an existing, current MIAB version. Here is what happened;

# Preliminaries

- apt update
- apt upgrade
- reboot, if needed
- no warnings, full green status

# 18.04 to 20.04

- edit **/etc/update-manager/release-upgrades** from **never** to **lts**
- do-release-upgrade to Focal
	- There will be warnings about running this upgrade over ssh. Continue.
	- I get an python backtrace error about no key for ubuntu-minimal
	- **There was no obvious way to restart the do-release-upgrade process, so I'm on my own.
- apt upgrade
- apt dist-upgrade
- Add back in the Ubuntu main repository for focal which was removed..
- apt update
- **fix a terrible problem with grub conflicts by purging a bunch of grub packages and reinstalling grub2**
- Answer Yes to all the questions about installing the Ubuntu version. this will revert all MIAB changes but will also make sure I get up to date confs to start with
- apt autoremove
- once all packages are updated, reboot
- pick through your sources list and make sure you have all of the security and updates repositories, which do-release-upgrade had disabled...
- apt update
- apt upgrade
- apt autoremove
- reboot

# 20.04 to 22.04

- do-release-upgrade
	- Same error about ubuntu-minimal, so process completely fails again.
- apt full-upgrade
- apt autoremove
- edit sources.list to include everything
- apt full-upgrade
- apt autoremove
- reboot (lucky this time)

# Mail-In-A-Box

- git checkout jammyjellyfish-everything (or your favorite candidate)
- cd mailinabox
- setup/start.sh
- got an error with the management venv

```
FAILED: /usr/local/lib/mailinabox/env/bin/pip install --upgrade pip
-----------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/mailinabox/env/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/utils/logging.py", line 13, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 40, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/local/lib/mailinabox/env/lib/python3.6/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
  File "/usr/local/lib/mailinabox/env/lib/python3.6/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
ImportError: cannot import name 'dist'
-----------------------------------------
```
- Python has upgrade major versions since this was run, so the venv needs to be recreated
```
rm -Rf /usr/local/lib/mailinabox/env
```
- rerun setup/start.sh
- reboot box

# Conclusions

It is a really bad idea to try this on a system where you have data that you care about. Not only does the distro-provided upgrade path not always work, but because you are updating things like grub (maybe more than once) you may find yourself in a position where the machine is unbootable and data recovery is difficult. Best to have backups and once you have backups, its easier and cleaner to start with a fresh system.

**Comment by bf** [comment]
Thank you, this helped me resolved a bugged upgrade from ubuntu 18 to 22
