### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Object of class SysvSemaphore could not be converted to string in /usr/local/lib/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php:45

### ISSUE THREAD

**Issue by Pranav-Dakshina** [mail-in-a-box/mailinabox#2177]
I ran into this Error when I upgraded from Ubuntu 22.04 to 18.04

```
Installing Z-Push (Exchange/ActiveSync server)...

FAILED: php8.0 /usr/local/lib/z-push/z-push-admin.php -a fixstates
-----------------------------------------

Validating and fixing states (this can take some time):
        17:48:27 Checking username casings: Processed: 4 - Converted: 0 - Removed: 0
        17:48:28 Checking available devicedata & user linking: PHP Fatal error:  Uncaught Error: Object of class SysvSemaphore could not be converted to string in /usr/local/lib/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php:45
Stack trace:
#0 /usr/local/lib/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php(45): sprintf()
#1 /usr/local/lib/z-push/lib/core/interprocessdata.php(87): IpcSharedMemoryProvider->__construct()
#2 /usr/local/lib/z-push/lib/default/simplemutex.php(34): InterProcessData->__construct()
#3 /usr/local/lib/z-push/lib/default/filestatemachine.php(203): SimpleMutex->__construct()
#4 /usr/local/lib/z-push/lib/utils/zpushadmin.php(943): FileStateMachine->LinkUserDevice()
#5 /usr/local/lib/z-push/z-push-admin.php(1223): ZPushAdmin::FixStatesDeviceToUserLinking()
#6 /usr/local/lib/z-push/z-push-admin.php(547): ZPushAdminCLI::CommandFixStates()
                                                                                #7 /usr/local/lib/z-push/z-push-admin.php(61): ZPushAdminCLI::RunCommand()
#8 {main}
  thrown in /usr/local/lib/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php on line 45 
```

**Comment by AussieTerror** [comment]
I had the same happen around zpush and spent some time trying to resolve it with no luck, I decided to just build a new server and migrate as per the 14.04 to 18.04 process..

**Comment by jvolkenant** [comment]
I tried the fix suggested here https://forum.kopano.io/topic/3885/z-push-with-zimbra-backend-php-8-0-not-working/5 but was still not able to reliably sync mail with activesync and 22.04.

I tried the fork here https://github.com/umgfoin/Z-Push/tree/php8.x with similar problems.  I hope there is more progress made on that fork, but will wait until the new year before revisiting.

If anyone has been able to use z-push with 22.04 + v60 i'd love to hear about it.

**Comment by jvolkenant** [comment]
Also The command `php8.0 /usr/local/lib/z-push/z-push-admin.php -a fixstates` needs an `>/dev/null 2>&1 || true` so it doesn't die during install

**Comment by jvolkenant** [comment]
cinergi's recommendation from here https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/53 seems to be promising, running v60 with these changes below seem to work better than https://github.com/umgfoin/Z-Push/tree/php8.x I tried last week.

> Edit /usr/local/lib/z-push/backend/ipcsharedmemory/ipcsharedmemoryprovider.php as per [this post](https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/13).
   Edit /usr/local/lib/z-push/policies.ini as per the above post.
   Add the symbolic links as per [this post](https://discourse.mailinabox.email/t/version-60-for-ubuntu-22-04-is-released/9558/43).
   Edit /usr/local/lib/z-push/backend/caldav/caldav.php as per the end of [this thread 2](https://forum.kopano.io/topic/3680/caldav-sync-error-unsupported-operand-types-string-int).

**Comment by matidau** [comment]
#2236
PR to fix this with updated repo

**Comment by bwmravec** [comment]
matidau's PR is fixing the issue with installing Z-push on v61.1
