### ISSUE TITLE
Error emitted after following upgrade instructions for MIAB to 60.1

### ISSUE THREAD

**Issue by tdahbura** [mail-in-a-box/mailinabox#2210]
Steps performed:

- Backed up the old system using the instructions to create a backup. 
- Created a new server using ubuntu 22
- Installed MIAB 60.1 on the new host
- Restored from the backup off the old host
- Re-ran the sudo mailinabox command after the restore completed

The following message gets emitted during the next cloud portions of the sudo mailinabox command execution:
Nextcloud is already latest version
Error: stepping, UNIQUE constraint failed: oc_users_external.uid, oc_users_external.backend (19)

Here is a full dump of the output of the sudo mailinabox command on the new host:
Primary Hostname: box.fullmoonmanor.net
Public IP Address: xx.xxx.xxx.xxx
Private IP Address: xxx.xxx.xxx.xxx
Mail-in-a-Box Version:  v60.1

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Nextcloud is already latest version
Error: stepping, UNIQUE constraint failed: oc_users_external.uid, oc_users_external.backend (19)
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
updated DNS: OpenDKIM configuration

-----------------------------------------------

Your Mail-in-a-Box is running.

I am concerned that this error message is popping up after a believed to be successful upgrade?  Would like to know if this is normal and it is safe to run the new box?

The above message appears every time a sudo mailinabox is executed on the new host.

Thx
Tony

**Comment by tdahbura** [comment]
The first sudo mailinabox command after doing a restore from backups had a long run of next cloud commands including the beginning that looks like-this is a lot of output but pasting here if it may be of use:
Upgrading to Nextcloud version 21.0.7

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: contacts
Disabled incompatible app: user_external
Updating <federation> ...
Updated <federation> to 1.11.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.9.0
Updating <oauth2> ...
Updated <oauth2> to 1.9.0
Updating <password_policy> ...
Updated <password_policy> to 1.11.0
Updating <files> ...
Updated <files> to 1.16.0
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.4.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [->--------------------------]   0%
Updated <dav> to 1.17.1
Updating <files_sharing> ...
Updated <files_sharing> to 1.13.1
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.11.0
Updating <files_versions> ...
Updated <files_versions> to 1.14.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.11.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.3.1
Updating <comments> ...
Updated <comments> to 1.11.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.10.0
Updating <notifications> ...
Updated <notifications> to 2.9.0
Updating <systemtags> ...
Updated <systemtags> to 1.11.0
Updating <theming> ...
Updated <theming> to 1.12.0
Updating <accessibility> ...
Migrate old user config
 Done
    1/1 [============================] 100%
Updated <accessibility> to 1.7.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.2.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.11.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.1.1
Updating <files_rightclick> ...
Updated <files_rightclick> to 1.0.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.10.0
Updating <logreader> ...
Updated <logreader> to 2.6.0
Updating <privacy> ...
Updated <privacy> to 1.5.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.11.0
Updating <recommendations> ...
Updated <recommendations> to 1.0.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.11.0
Updating <settings> ...
Updated <settings> to 1.3.0
Updating <support> ...
Updated <support> to 1.4.0
Updating <survey_client> ...
Updated <survey_client> to 1.9.0
Updating <text> ...
Updated <text> to 3.2.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.10.0
Updating <updatenotification> ...
Updated <updatenotification> to 1.11.0
Updating <user_status> ...
Updated <user_status> to 1.1.1
Updating <viewer> ...
Updated <viewer> to 1.5.0
Updating <weather_status> ...
Updated <weather_status> to 1.1.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore 
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app privacy in appstore
Checked for update of app "privacy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in appstore 
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore 
Checking for update of app settings in appstore
Checked for update of app "settings" in appstore 
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore 
Checking for update of app support in appstore
Checked for update of app "support" in appstore 
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app text in appstore
Checked for update of app "text" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app user_status in appstore
Checked for update of app "user_status" in appstore 
Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore 
Checking for update of app weather_status in appstore
Checked for update of app "weather_status" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore 
Checking for update of app contacts in appstore
Checked for update of app "contacts" in appstore 
Checking for update of app user_external in appstore
Checked for update of app "user_external" in appstore 
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Check indices of the share table.
Check indices of the filecache table.
Adding additional size index to the filecache table, this can take some time...
Filecache table updated successfully.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
All tables already up to date!

Upgrading to Nextcloud version 22.2.6

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: contacts
Updating <federation> ...
Updated <federation> to 1.12.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.10.0
Updating <oauth2> ...
Updated <oauth2> to 1.10.0
Updating <password_policy> ...
Updated <password_policy> to 1.12.0
Updating <user_external> ...
Updated <user_external> to 3.0.0
Updating <files> ...
Updated <files> to 1.17.0
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.5.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [->--------------------------]   0%
Clean up old calendar subscriptions from deleted users that were not cleaned-up
 Done
    0/0 [----->----------------------]   0%
Updated <dav> to 1.20.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.14.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.12.0
Updating <files_versions> ...
Updated <files_versions> to 1.15.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.12.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.4.0
Updating <comments> ...
Updated <comments> to 1.12.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.11.0
Updating <notifications> ...
Updated <notifications> to 2.10.1
Updating <systemtags> ...
Updated <systemtags> to 1.12.0
Updating <theming> ...
Updated <theming> to 1.13.0
Updating <accessibility> ...
Migrate old user config
 Done
    1/1 [============================] 100%
Updated <accessibility> to 1.8.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.3.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.12.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.3.1
Updating <files_rightclick> ...
Updated <files_rightclick> to 1.1.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.11.0
Updating <logreader> ...
Updated <logreader> to 2.7.0
Updating <privacy> ...
Updated <privacy> to 1.6.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.12.0
Updating <recommendations> ...
Updated <recommendations> to 1.1.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.12.0
Updating <settings> ...
Updated <settings> to 1.4.0
Updating <support> ...
Updated <support> to 1.5.0
Updating <survey_client> ...
Updated <survey_client> to 1.10.0
Updating <text> ...
Updated <text> to 3.3.1
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.11.0
Updating <updatenotification> ...
Updated <updatenotification> to 1.12.0
Updating <user_status> ...
Updated <user_status> to 1.2.0
Updating <viewer> ...
Updated <viewer> to 1.6.0
Updating <weather_status> ...
Updated <weather_status> to 1.2.0
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Check indices of the share table.
Check indices of the filecache table.
Adding additional path index to the filecache table, this can take some time...
Filecache table updated successfully.
Adding additional size index to the filecache table, this can take some time...
Filecache table updated successfully.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Adding properties_pathonly_index index to the oc_properties table, this can take some time...
oc_properties table updated successfully.
Check indices of the oc_jobs table.
Adding job_lastcheck_reserved index to the oc_jobs table, this can take some time...
oc_properties table updated successfully.
All tables already up to date!

Upgrading to Nextcloud version 23.0.10

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: contacts
Updating <federation> ...
Updated <federation> to 1.13.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.11.0
Updating <oauth2> ...
Updated <oauth2> to 1.11.0
Updating <password_policy> ...
Updated <password_policy> to 1.13.0
Updating <files> ...
Updated <files> to 1.18.0
Updating <circles> ...
Updated <circles> to 23.1.2
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.6.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [->--------------------------]   0%
Clean up old calendar subscriptions from deleted users that were not cleaned-up
 Done
    0/0 [----->----------------------]   0%
Updated <dav> to 1.21.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.15.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.13.0
Updating <files_versions> ...
Updated <files_versions> to 1.16.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.13.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.5.0
Updating <comments> ...
Updated <comments> to 1.13.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.12.0
Updating <notifications> ...
Updated <notifications> to 2.11.2
Updating <systemtags> ...
Updated <systemtags> to 1.13.0
Updating <theming> ...
Updated <theming> to 1.14.0
Updating <accessibility> ...
Migrate old user config
 Done
    1/1 [============================] 100%
Updated <accessibility> to 1.9.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.4.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.13.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.4.0
Updating <files_rightclick> ...
Updated <files_rightclick> to 1.2.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.12.0
Updating <logreader> ...
Updated <logreader> to 2.8.0
Updating <privacy> ...
Updated <privacy> to 1.7.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.13.0
Updating <recommendations> ...
Updated <recommendations> to 1.2.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.13.0
Updating <settings> ...
Updated <settings> to 1.5.0
Updating <support> ...
Updated <support> to 1.6.0
Updating <survey_client> ...
Updated <survey_client> to 1.11.0
Updating <text> ...
Updated <text> to 3.4.1
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.12.0
Updating <updatenotification> ...
Updated <updatenotification> to 1.13.0
Updating <user_status> ...
Updated <user_status> to 1.3.1
Updating <viewer> ...
Updated <viewer> to 1.7.0
Updating <weather_status> ...
Updated <weather_status> to 1.3.0
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Check indices of the oc_jobs table.
Done.
All tables already up to date!
Nextcloud is already latest version
Error: stepping, UNIQUE constraint failed: oc_users_external.uid, oc_users_external.backend (19)
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...

**Comment by kiekerjan** [comment]
[This](https://github.com/mail-in-a-box/mailinabox/pull/2159#issuecomment-1247626997) might help.
What output do you get when you do:
`sqlite3 owncloud.db`
`select * from oc_users_external;`

You can find the owncloud database in the miab storage directory under owncloud, by default it's /home/user-data/owncloud

**Comment by downtownallday** [comment]
From the [readme](https://github.com/nextcloud/user_external#readme) 

> Warning: If you are [upgrading from versions <0.6.0](https://github.com/nextcloud/user_external/releases/tag/v0.6.0), beside adapting your config.php you also have to change the backend column in the users_external table of the database. In your pre 0.6.0 database it may look like {127.0.0.1:993/imap/ssl/readonly}INBOX or similar, but now it has to be just 127.0.0.1 for everything to work flawless again.

The download page shows user_external v0.6 being released on Mar 15, 2019.

**Comment by digititus** [comment]
Also seeing this error on a clean install Ubuntu 22.04 with restored data from v0.57a

> Error: stepping, UNIQUE constraint failed: oc_users_external.uid, oc_users_external.backend (19)

> sqlite> select * from oc_users_external;
Shows a number of duplicates

**Comment by haslinger** [comment]
Seeing this error as well. If I can provide any additional infos needed, please let me know.

**Comment by tdahbura** [comment]
team-
is there a fix to resolve this or a command that can be run during or post migration to clean this error up?  This error continues to appear on all subsequent sudo mailinabox runs?
appreciate the support!

**Comment by tdahbura** [comment]
I tried another migration today from 57a to 61.1 and after doing the restore from my 57a box using duplicity and then running a final sudo mailinabox I received the following output and a crash:

Mail-in-a-Box Version:  v61.1

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Synchronizing state of fail2ban.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable fail2ban
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
bayes: synced databases from journal in 0 seconds: 2828 unique entries (3150 total entries)
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Updating database schema (2021081000)... [OK]
Updating database schema (2021100300)... [OK]
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2023-01-29-11:58:28...

Upgrading to Nextcloud version 21.0.7

An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 11 database disk image is malformed in /usr/local/lib/owncloud/lib/private/DB/Connection.php:85
Stack trace:
#0 /usr/local/lib/owncloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /usr/local/lib/owncloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /usr/local/lib/owncloud/lib/private/DB/Connection.php(231): Doctrine\DBAL\Connection->executeQuery()
#3 /usr/local/lib/owncloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /usr/local/lib/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /usr/local/lib/owncloud/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /usr/local/lib/owncloud/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
#7 /usr/local/lib/owncloud/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
#8 /usr/local/lib/owncloud/lib/private/legacy/OC_App.php(975): OC\AppConfig->getValues()
#9 /usr/local/lib/owncloud/lib/private/Server.php(682): OC_App::getAppVersions()
#10 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#11 /usr/local/lib/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#13 /usr/local/lib/owncloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query()
#14 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#15 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(177): OC\AppFramework\Utility\SimpleContainer->get()
#16 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /usr/local/lib/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#19 /usr/local/lib/owncloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query()
#20 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#21 /usr/local/lib/owncloud/lib/private/Server.php(1041): OC\AppFramework\Utility\SimpleContainer->get()
#22 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#23 /usr/local/lib/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#25 /usr/local/lib/owncloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query()
#26 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#27 /usr/local/lib/owncloud/lib/private/Server.php(2000): OC\AppFramework\Utility\SimpleContainer->get()
#28 /usr/local/lib/owncloud/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#29 /usr/local/lib/owncloud/lib/private/Server.php(430): OC\Files\View->__construct()
#30 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#31 /usr/local/lib/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#33 /usr/local/lib/owncloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query()
#34 /usr/local/lib/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#35 /usr/local/lib/owncloud/lib/private/Server.php(1363): OC\AppFramework\Utility\SimpleContainer->get()
#36 /usr/local/lib/owncloud/lib/base.php(588): OC\Server->boot()
#37 /usr/local/lib/owncloud/lib/base.php(1076): OC::init()
#38 /usr/local/lib/owncloud/console.php(49): require_once('...')
#39 /usr/local/lib/owncloud/occ(11): require_once('...')

$

**Comment by tdahbura** [comment]
Looks like this is now OBE since 61 is now out. 61 however is not behaving nicely from my 57a backup and restore - with nextcloud 😒

**Comment by kiekerjan** [comment]
These are instructions that might be used to resolve the issue.
**Before you start, make a backup of the owncloud database**
```
cd /home/user-data/owncloud
cp owncloud.db owncloud.db.backup
```

Check if the issue is caused by duplicate entries in the database

```sqlite3 owncloud.db "select * from oc_users_external;"```

This returns all rows in the affected table of the database. You can easily see here if multiple duplicate entries are present.**Make note of which lines should be deleted.**

First run the following command:

```sqlite3 owncloud.db "SELECT * FROM oc_users_external WHERE EXISTS (SELECT 1 FROM oc_users_external p2 WHERE oc_users_external.uid = p2.uid AND oc_users_external.rowid > p2.rowid);"```

This shows the rows that will be deleted by the command below. **Make sure that there are not more lines shown here than that should be removed as you noted after the previous command before proceeding.**

This command will delete the duplicate rows:

```sqlite3 owncloud.db "DELETE FROM oc_users_external WHERE EXISTS (SELECT 1 FROM oc_users_external p2 WHERE oc_users_external.uid = p2.uid AND oc_users_external.rowid > p2.rowid);"```

Check the contents of the table:
```owncloud.db "select * from oc_users_external;"```
No more duplicate rows should be present.

This should show something like:
```
127.0.0.1|user1@domain.com|
127.0.0.1|user2@domain.com|
127.0.0.1|user3@domain.com|
127.0.0.1|user6@anotherdomain.com|
```

If this does not only show ```127.0.0.1``` use the following command to make sure the backend column is set correctly:
```sqlite3 owncloud.db "UPDATE oc_users_external SET backend='127.0.0.1';"```

If at any time you get a response you don't expect or can't explain, stop proceeding.

**Comment by tdahbura** [comment]
this is very helpful.  I do see two duplicate rows in the table you pointed out
most rows in the table are of the form:
**tony@dahbura.com|{127.0.0.1:993/imap/ssl/novalidate-cert}|**

But two of my users (1 is the admin user for my MIAB) have two entries.
For example I have admin@fullmoonmanor.net and there are two entries for this user:
**admin@fullmoonmanor.net|{127.0.0.1:993/imap/ssl/novalidate-cert}|
admin@fullmoonmanor.net|127.0.0.1|**

Should I follow the above and delete the two duplicates that do not match the format all the users are in?  And is this okay that one of these users is my admin user for MIAB?

**Comment by kiekerjan** [comment]
I believe the answer to your first two questions is yes. The backend column should have the value 127.0.0.1 as per the [user external instructions](https://github.com/nextcloud/user_external#readme).
But before you do anything, can you provide the output to he command:
```sqlite3 owncloud.db "PRAGMA table_info(oc_users_external);"```

which gives me 
```
0|backend|VARCHAR(128)|1|''|2
1|uid|VARCHAR(64)|1|''|1
2|displayname|VARCHAR(64)|0|NULL|0
```
and confirm you're on Mail in a Box 60 or 61?
Your table structure seems to be different to mine, which might have to do with the original installation of your server. Just to be sure the delete commands does no harm.

**Comment by tdahbura** [comment]
I was doing the query commands on my v57a server.  I will attempt another backup of my 57a and restore to a new 61 server.

I will run the below command once that is done.  I did get the column names from my 57a oc_users_external table and the column names match below but will run the pragma command.

**Comment by kiekerjan** [comment]
Ok, so your table is not completely different. You can run the sql commands just fine. Or if you're into that, remove the duplicate lines manually, then set `backend` to `127.0.0.1` for all rows.

**Comment by binarykitchen** [comment]
I concur, @kiekerjan's tip at https://github.com/mail-in-a-box/mailinabox/issues/2210#issuecomment-1426775364 fixed it for me just today.

**Comment by zacuke** [comment]
What is the SQL statement to add the unique constraint after manually fixing the database? I re-ran mailinabox setup, but it doesn't re-run the nextcloud setup.

Is there any other SQL statements that get missed or just this unique constraint?

**Comment by kiekerjan** [comment]
No conmands mentioned in this issue remove the unique constraint from the table. Which leaves the questions:
- how do you know the unique constraint ia gone?
- what did you do to *manually fixing" the database?

**Comment by zacuke** [comment]
> No conmands mentioned in this issue remove the unique constraint from the table. Which leaves the questions:
> 
> * how do you know the unique constraint ia gone?
> * what did you do to *manually fixing" the database?

This error indicates a unique constraint is not applied during the nextcloud update process 

> Error: stepping, UNIQUE constraint failed: oc_users_external.uid, oc_users_external.backend (19)

Manually fixing the database by following  instructions in comment above https://github.com/mail-in-a-box/mailinabox/issues/2210#issuecomment-1426775364

But since the owncloud.db update is already applied, when I re-rain sudo mailinabox, it did not upgrade the owncloud.db database again, so I'm curious if there is a missing unique constraint to owncloud.db
