### ISSUE TITLE
I get a 500 Internal Server Error when I try to set up a service compatible with S3.

### ISSUE THREAD

**Issue by horyu1234** [mail-in-a-box/mailinabox#2266]
mail-in-a-box version: `v62`
compatible with S3 service: `Cloudflare R2`

When I click the Save Settings button, a message is displayed stating that an internal server error has occurred.

## Backup Setting
![image](https://github.com/mail-in-a-box/mailinabox/assets/9531279/638ad117-d1d9-45a4-b6e6-60c8c7136edc)

## Error Screen
![image](https://github.com/mail-in-a-box/mailinabox/assets/9531279/3d379b45-7460-4e83-b778-3cad30ad9ad8)

## Error Log (`/var/log/syslog`)
```
May 24 01:56:49 box start[1865]: [2023-05-24 01:56:49,348] ERROR in app: Exception on /system/backup/config [POST]
May 24 01:56:49 box start[1865]: Traceback (most recent call last):
May 24 01:56:49 box start[1865]:   File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
May 24 01:56:49 box start[1865]:     response = self.full_dispatch_request()
May 24 01:56:49 box start[1865]:   File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
May 24 01:56:49 box start[1865]:     rv = self.handle_user_exception(e)
May 24 01:56:49 box start[1865]:   File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
May 24 01:56:49 box start[1865]:     rv = self.dispatch_request()
May 24 01:56:49 box start[1865]:   File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
May 24 01:56:49 box start[1865]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
May 24 01:56:49 box start[1865]:   File "/root/mailinabox/management/daemon.py", line 75, in newview
May 24 01:56:49 box start[1865]:     return viewfunc(*args, **kwargs)
May 24 01:56:49 box start[1865]:   File "/root/mailinabox/management/daemon.py", line 635, in backup_set_custom
May 24 01:56:49 box start[1865]:     return json_response(backup_set_custom(env,
May 24 01:56:49 box start[1865]:   File "/root/mailinabox/management/backup.py", line 543, in backup_set_custom
May 24 01:56:49 box start[1865]:     list_target_files(config)
May 24 01:56:49 box start[1865]:   File "/root/mailinabox/management/backup.py", line 499, in list_target_files
May 24 01:56:49 box start[1865]:     bucket_objects = s3.list_objects_v2(Bucket=bucket, Prefix=path)['Contents']
May 24 01:56:49 box start[1865]: KeyError: 'Contents'
May 24 01:56:49 box Exception on /system/backup/config [POST]#012Traceback (most recent call last):#012  File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/mailinabox/env/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request#012    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)#012  File "/root/mailinabox/management/daemon.py", line 75, in newview#012    return viewfunc(*args, **kwargs)#012  File "/root/mailinabox/management/daemon.py", line 635, in backup_set_custom#012    return json_response(backup_set_custom(env,#012  File "/root/mailinabox/management/backup.py", line 543, in backup_set_custom#012    list_target_files(config)#012  File "/root/mailinabox/management/backup.py", line 499, in list_target_files#012    bucket_objects = s3.list_objects_v2(Bucket=bucket, Prefix=path)['Contents']#012KeyError: 'Contents'

```

**Comment by horyu1234** [comment]
## Cloudflare R2 screen

![image](https://github.com/mail-in-a-box/mailinabox/assets/9531279/7c074e01-b5ed-4d93-b8c8-140771b2473e)

![image](https://github.com/mail-in-a-box/mailinabox/assets/9531279/a15f2619-010c-4e57-adcb-25f6b5b7deb1)

**Comment by volkv** [comment]
Try to remove `https://` from r2 host and make sure your backup folder exists

**Comment by horyu1234** [comment]
Issue resolved, closed.

The cause was a problem that occurred because the path folder to be backed up was not created in R2.

I thought the folder would be created automatically, but it wasn't.
