### ISSUE TITLE
Installations fails/times out with: "FAILED: add-apt-repository -y ppa:duplicity-team/duplicity-release-git"

### ISSUE THREAD

**Issue by gittbuh** [mail-in-a-box/mailinabox#2450]
Hi there,

I am trying to install MIAB in a VPS (KVM) 1GB memory, 10GB disk, following the official instructions. The script appears to run ok and just after I have selected my hostname, the installation hangs/times out with a  "FAILED: add-apt-repository -y ppa:duplicity-team/duplicity-release-git" message. The full error details pasted below:

"FAILED: add-apt-repository -y ppa:duplicity-team/duplicity-release-git
-----------------------------------------
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 347, in main                                                 
    shortcut = handler(source, **shortcut_params)                                                       
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler     
    return handler(shortcut, **kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
    if self.lpppa.publish_debug_symbols:
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam
    self._lpteam = self.lp.people(self.teamname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp
    self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously 
    return cls(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__                   
    super(Launchpad, self).__init__(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in __init__
    self._wadl = self._browser.get_wadl_application(self._root_uri)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request
    response, content = self._request_and_retry(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry
    response, content = self._connection.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
    response, content = super(LaunchpadOAuthAwareHttp, self)._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 184, in _request
    return super(RestfulHttp, self)._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1153, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 110] Connection timed out"

Any ideas? Thanks in advance.

**Comment by gittbuh** [comment]
I googled the thing and found the solution here: https://discourse.mailinabox.email/t/unable-to-install-fails-solved/9879/25

Install bind before miab and edit /etc/bind/named.conf.options, change "dnssec-validation auto" to "dnssec-validation yes"

Thanks a lot to the person who posted this, I would have never figured this out. 

No idea why this is happening to some of us though. It should probably be mentioned in the installation guide if it isn't already.

**Comment by ryan-james-smith** [comment]
Another possible issue people may run into is if they run for example an ec2 instance with a private ipv6 I founf I need to at least temporarily disable ipv6 while I do the update as it tried to translate the repository via ipv6 instead of ipv4 but only throws the error listed.
To temporarily disable ipv6:
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
then run the install, with the above 3 lines ipv6 will be reenabled on reboot.

**Comment by dsmith2001** [comment]
In my case, there was an issue with the way the IPs were set up on my VPS because even a ping or traceroute for an IPv6 address wouldn't work and pinging the IPv6 address of my VPS didn't work either.

I had to remove the IPs assigned to my network interfaces via `sudo ip addr flush dev [interface]` and then `sudo netplan apply`.
**WARNING: Your mileage may vary. This assumes that you are connected via VNC and your machine/provider actually uses netplan with a valid configuration file.**
