### ISSUE TITLE
Status Checks Change Notice: Missing privilege separation directory: /run/sshd

### ISSUE THREAD

**Issue by benbois** [mail-in-a-box/mailinabox#2462]
Hi there,
I received this email error [Status Checks Change Notice] this morning after a last commands in server yesterday: `sudo apt update && sudo apt dist-upgrade`

```
Missing privilege separation directory: /run/sshd
Traceback (most recent call last):
  File "/home/leoon/mailinabox/management/utils.py", line 193, in get_ssh_config_value
    output = shell('check_output', ['sshd', '-T'])
  File "/home/leoon/mailinabox/management/utils.py", line 127, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sshd', '-T']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leoon/mailinabox/management/status_checks.py", line 1099, in <module>
    run_and_output_changes(env, pool)
  File "/home/leoon/mailinabox/management/status_checks.py", line 940, in run_and_output_changes
    run_checks(True, env, cur, pool)
  File "/home/leoon/mailinabox/management/status_checks.py", line 50, in run_checks
    if not run_services_checks(env, output, pool):
  File "/home/leoon/mailinabox/management/status_checks.py", line 72, in run_services_checks
    ret = pool.starmap(check_service, ((i, service, env) for i, service in enumerate(get_services())), chunksize=1)
  File "/home/leoon/mailinabox/management/status_checks.py", line 33, in get_services
    { "name": "SSH Login (ssh)", "port": get_ssh_port(), "public": True, },
  File "/home/leoon/mailinabox/management/utils.py", line 183, in get_ssh_port
    port_value = get_ssh_config_value("port")
  File "/home/leoon/mailinabox/management/utils.py", line 197, in get_ssh_config_value
    except subprocess.CalledProcessError:
NameError: name 'subprocess' is not defined
```

What I have to do to fix this?

**Comment by downtownallday** [comment]
I believe all that's needed is #2425

**Comment by benbois** [comment]
Thanks @downtownallday, the #2425 fixed this issue!
