### ISSUE TITLE
CronTab StatusChecks

### ISSUE THREAD

**Issue by bizonix** [mail-in-a-box/mailinabox#360]
/etc/cron.daily/mailinabox-statuschecks:
Traceback (most recent call last):
 File "/root/mailinabox/management/status_checks.py", line 901, in <module>
   run_and_output_changes(env, pool, sys.argv[-1] == "--smtp")
 File "/root/mailinabox/management/status_checks.py", line 800, in run_and_output_changes
   out.add_warning("Removed.")
AttributeError: 'FileOutput' object has no attribute 'add_warning'
run-parts: /etc/cron.daily/mailinabox-statuschecks exited with return code 1

**Comment by JoshData** [comment]
Thanks! Fix committed.
