### ISSUE TITLE
Your system may be in an inconsistent state now. We're terribly sorry. A re-install from a backup might be the best way to continue.

### ISSUE THREAD

**Issue by Xoib** [mail-in-a-box/mailinabox#395]
Hello,

I am currently in 0.08.
Here is the output of the upgrade failing :

```
root@ks:~# ./bootstrap.sh
Updating Mail-in-a-Box to v0.09 . . .
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.


Running migration to Mail-in-a-Box #4...
Error: duplicate column name: privileges

Error running the migration script:

Command '['sqlite3', '/home/user-data/mail/users.sqlite', "ALTER TABLE users ADD privileges TEXT NOT NULL DEFAULT ''"]' returned non-zero exit status 1

Your system may be in an inconsistent state now. We're terribly sorry. A re-install from a backup might be the best way to continue.
```

**Comment by Xoib** [comment]
That was yesterday, this morning I had this output in the daily status check : 

```
/etc/cron.daily/mailinabox-statuschecks:
Traceback (most recent call last):
  File "/root/mailinabox/management/status_checks.py", line 14, in <module>
    from dns_update import get_dns_zones, build_tlsa_record, get_custom_dns_config, get_secondary_dns
  File "/root/mailinabox/management/dns_update.py", line 12, in <module>
    from mailconfig import get_mail_domains
  File "/root/mailinabox/management/mailconfig.py", line 5, in <module>
    from email_validator import validate_email as validate_email_, EmailNotValidError
ImportError: No module named 'email_validator'
run-parts: /etc/cron.daily/mailinabox-statuschecks exited with return code 1
```

**Comment by JoshData** [comment]
What's the contents of your `/home/user-data/mailinabox.version` file?

See: https://discourse.mailinabox.email/t/upgrade-failure-very-concerned/461/3

**Comment by Xoib** [comment]
It's 3.

So it manually edit it to 4 or 5 ? As obviously the problem seems migration_4 within the migrate script.

**Comment by JoshData** [comment]
I think 4 will do the trick.

**Comment by Xoib** [comment]
Ok thanks. Btw you recommendation in the other post is to delete mailinabox.version, but if you do that it will skip whatever the migration step you really needed before the bug ?

**Comment by Xoib** [comment]
Yep it did the trick. But I am wondering why it happened.
