### ISSUE TITLE
"Something went wrong, sorry." => No such file or directory: 'sshd'

### ISSUE THREAD

**Issue by omniomi** [mail-in-a-box/mailinabox#444]
When I attempt to view the System Status Checks page I get the error "Something went wrong, sorry."

omniomi@omx:~/mailinabox$ sudo management/status_checks.py

System
======
Traceback (most recent call last):
  File "management/status_checks.py", line 921, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "management/status_checks.py", line 25, in run_checks
    if not run_services_checks(env, output, pool):
  File "management/status_checks.py", line 70, in run_services_checks
    { "name": "SSH Login (ssh)", "port": get_ssh_port(), "public": True, },
  File "management/status_checks.py", line 45, in get_ssh_port
    output = shell('check_output', ['sshd', '-T'])
  File "/home/omniomi/mailinabox/management/utils.py", line 149, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 603, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'sshd'

**Comment by JoshData** [comment]
Thanks for reporting the problem! Fixed now.
