### ISSUE TITLE
Users won't load with a 45gb Mailbox 

### ISSUE THREAD

**Issue by Futurama56** [mail-in-a-box/mailinabox#531]
I have a user with a 45GB+ mailbox that is blocking me from accessing Users.

All I get is:

Error

Something went wrong, sorry.

And NO users are displayed.

**Comment by Futurama56** [comment]
The timeout happens after only 30 seconds - not enough time to scan a directory that big!

**Comment by Futurama56** [comment]
+1 any temporary fix?  Our user admin is blocked.

**Comment by JoshData** [comment]
Can you tell me how long it takes to run `sudo du -hs /home/user-data/mail`?

I don't have an easy fix for this, unless you go into the Mail-in-a-Box source code and disable the part that is checking how large each user account is (at [management/mailconfig.py#L133](https://github.com/mail-in-a-box/mailinabox/blob/master/management/mailconfig.py#L133)).

(If we switched to Dovecot's mdbox mail storage format (see #510) we might be able to make this work better because there would be fewer files on disk. But I don't know how much better this would make things.)

**Comment by Futurama56** [comment]
More than 3 minutes!  175G

I have tried disabling the line - at 
https://github.com/mail-in-a-box/mailinabox/blob/master/management/mailconfig.py#L133

Doesn't seem to help

**Comment by Hoekynl** [comment]
Delete some of his trash?
it's located at : /home/user-data/mail/mailboxes/<domain>/<user>/.Trash/cur
.Trash is hidden, so you might need to enable "View hidden files and folders"

**Comment by Futurama56** [comment]
@Hoekynl I can't delete user mail.  That doesn't seem like much of a solution.

**Comment by JoshData** [comment]
@Futurama56 After you disable the line, run `sudo service restart mailinabox` to have the control panel pick up the change.

**Comment by Futurama56** [comment]
I tried that - it still throws the error!

**Comment by Futurama56** [comment]
Now getting :

Exception on /mail/users [GET]#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012    raise value#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/usr/local/bin/mailinabox-daemon", line 49, in newview#012    return viewfunc(*args, **kwargs)#012  File "/usr/local/bin/mailinabox-daemon", line 138, in mail_users#012    return json_response(get_mail_users_ex(env, with_archived=True, with_slow_info=True))#012  File "/root/mailinabox/management/mailconfig.py", line 155, in get_mail_users_ex#012    domain = get_domain(user["email"])#012  File "/root/mailinabox/management/mailconfig.py", line 245, in get_domain#012    if as_unicode: ret = idna.decode(ret.encode('ascii'))#012  File "/usr/local/lib/python3.4/dist-packages/idna/core.py", line 383, in decode#012    result.append(ulabel(label))#012  File "/usr/local/lib/python3.4/dist-packages/idna/core.py", line 298, in ulabel#012    check_label(label)#012  File "/usr/local/lib/python3.4/dist-packages/idna/core.py", line 252, in check_label#012    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))#012idna.core.InvalidCodepoint: 


Codepoint U+003A at position 4 of '161:@ourdomain' not allowed

**Comment by Futurama56** [comment]
we have a @mydomain-something.com - which seems to be breaking it this:

# Sort aliases within each domain first by required-ness then lexicographically by address.
        for domain in domains:
                domain["aliases"].sort(key = lambda alias : (alias["required"], alias["address"]))
        return domains

def get_domain(emailaddr, as_unicode=True):
        # Gets the domain part of an email address. Turns IDNA
        # back to Unicode for display.
        ret = emailaddr.split('@', 1)[1]
        if as_unicode: ret = idna.decode(ret.encode('ascii'))
        return ret

**Comment by JoshData** [comment]
Looks like you snuck an invalid email address into the database? Pretty sure you can't have a colon in an email address.

**Comment by JoshData** [comment]
Or, actually, this should be just the domain part of an email address. Did you somehow create a user `something@161:@ourdomain`?

**Comment by Futurama56** [comment]
I have checked the db and didn't find the naked @ourdomain - without .com or other tld.  There was however one candidate as we use a @ourdomain-xxx.com

**Comment by Futurama56** [comment]
What is strange is we don't have any naked @ourdomain - all the mail/mailboxes folders end with .com

**Comment by Futurama56** [comment]
IT WORKED!  THANK YOU for Saving the Day!  

root@69.69.69.69:@ourdomain.com was the ghost!

**Comment by Futurama56** [comment]
Now I see "NaN TB" - we are on a 7TB disk - 
and things seem to break unless I turn off line 133 in mailconfig - (can't start mailinabox with it enabled)

But I do see sizes for archived boxes -

**Comment by JoshData** [comment]
Well we're just back to the original problem now - you have too large a mailbox and it's trying to compute the size of it.

**Comment by bronson** [comment]
https://github.com/mail-in-a-box/mailinabox/pull/510 might help this issue a little.  Switching to dbox (like it says in that PR) would probably help a lot.

**Comment by yeah** [comment]
FWIW I ran into the same issue. What helped (for now) was changing `with_slow_info` from `True` to `False` in line 151 of `/usr/local/bin/mailinabox-daemon` (that's in `def mail_users()`) and restarting the daemon with `sudo service mailinabox restart`.

I do like the idea of making the call to `du` on demand via a separate button as suggested in #851.
