### ISSUE TITLE
Empty DS files

### ISSUE THREAD

**Issue by webknjaz** [mail-in-a-box/mailinabox#785]
Hi,
I've `dns_update.do_dns_update()` generates empty `*.ds` files for all domains, except for default one:
```sh
➜  mailinabox git:(f3ad6b4) ll /etc/nsd/zones/*.ds
-rw-r--r-- 1 root root   0 Apr  3 20:23 /etc/nsd/zones/hack.dou.ua.txt.ds
-rw-r--r-- 1 root root   0 Apr  3 20:23 /etc/nsd/zones/hackraft.com.txt.ds
-rw-r--r-- 1 root root   0 Apr  3 20:23 /etc/nsd/zones/itkpi.pp.ua.txt.ds
-rw-r--r-- 1 root root   0 Apr  3 20:23 /etc/nsd/zones/kpi.pp.ua.txt.ds
-rw-r--r-- 1 root root   0 Apr  3 20:23 /etc/nsd/zones/lug.kpi.ua.txt.ds
-rw-r--r-- 1 root root 180 Apr  3 20:20 /etc/nsd/zones/mx.hack.dou.ua.txt.ds
-rw-r--r-- 1 root root   0 Apr  3 20:23 /etc/nsd/zones/timetable.pp.ua.txt.ds
```

This leads to the following error, while checking the configuration:
```python
➜  mailinabox git:(f3ad6b4) management/status_checks.py 

System
======
✓  All system services are running.
✓  SSH disallows password-based login.
✖  System updates have been installed and a reboot of the machine is required.
✓  administrator@mx.hack.dou.ua exists as a mail alias [=> wk@hack.dou.ua]
✓  The disk has 13.6 GB space remaining.

Network
=======
✓  Outbound mail (SMTP port 25) is not blocked.
✓  IP address is not blacklisted by zen.spamhaus.org.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "management/status_checks.py", line 264, in run_domain_checks_on_domain
    check_dns_zone_suggestions(domain, env, output, dns_zonefiles)
  File "management/status_checks.py", line 381, in check_dns_zone_suggestions
    check_dnssec(domain, env, output, dns_zonefiles)
  File "management/status_checks.py", line 391, in check_dnssec
    ds_keytag, ds_alg, ds_digalg, ds_digest = rr_ds.split("\t")[4].split(" ")
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "management/status_checks.py", line 918, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "management/status_checks.py", line 41, in run_checks
    run_domain_checks(rounded_values, env, output, pool)
  File "management/status_checks.py", line 241, in run_domain_checks
    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
IndexError: list index out of range
```

Could you please check this? I've tried to figure this out myself, but couldn't find the root of issue :(

**Comment by JoshData** [comment]
The thing will be to figure out why this command is failing:

https://github.com/mail-in-a-box/mailinabox/blob/master/management/dns_update.py#L576
