### ISSUE TITLE
Something went wrong on System Status Checks

### ISSUE THREAD

**Issue by georgetasioulis** [mail-in-a-box/mailinabox#944]
Hello,

After upgrading to v0.19b I was introduced to a "Something went wrong, sorry" error when logging in and visiting the System Status Checks.
All other pages work fine, emails can be sent and received etc.

This is the error in syslog:
```
Sep 21 11:50:50 mx Exception on /system/status [POST]#012multiprocessing.pool.RemoteTraceback: #012"""#012Traceback (most recent call last):#012  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker#012    result = (True, func(*args, **kwds))#012  File "/usr/lib/python3.4/multiprocessing/pool.py", line 47, in starmapstar#012    return list(itertools.starmap(args[0], args[1]))#012  File "/root/mailinabox/management/status_checks.py", line 342, in run_domain_checks_on_domain#012    check_web_domain(domain, rounded_time, ssl_certificates, env, output)#012  File "/root/mailinabox/management/status_checks.py", line 631, in check_web_domain#012    value = query_dns(domain, rtype)#012  File "/root/mailinabox/management/status_checks.py", line 683, in query_dns#012    return "; ".join(sorted(str(r).rstrip('.') for r in response))#012  File "/root/mailinabox/management/status_checks.py", line 683, in <genexpr>#012    return "; ".join(sorted(str(r).rstrip('.') for r in response))#012TypeError: __str__ returned non-string (type bytes)#012"""#012#012The above exception was the direct cause of the following exception:#012#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012    raise value#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/usr/local/bin/mailinabox-daemon", line 55, in newview#012    return viewfunc(*args, **kwargs)#012  File "/usr/local/bin/mailinabox-daemon", line 442, in system_status#012    run_checks(False, env, output, pool)#012  File "/root/mailinabox/management/status_checks.py", line 65, in run_checks#012    run_domain_checks(rounded_values, env, output, pool)#012  File "/root/mailinabox/management/status_checks.py", line 312, in run_domain_checks#012    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)#012  File "/usr/lib/python3.4/multiprocessing/pool.py", line 268, in starmap#012    return self._map_async(func, iterable, starmapstar, chunksize).get()#012  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get#012    raise self._value#012TypeError: __str__ returned non-string (type bytes)
```

and this is when I run status_checks.py manually
```
root@mx:~/mailinabox# management/status_checks.py

System
======
✓  All system services are running.
✓  SSH disallows password-based login.
✓  System software is up to date.
✓  Mail-in-a-Box is up to date. You are running version v0.19b.
✓  System administrator address exists as a mail alias. [administrator@mx.fusionedmail.com ↦ george@fusionedmail.com]
✓  The disk has 18.2 GB space remaining.
✓  System memory is 38% free.

Network
=======
✓  Firewall is active.
✓  Outbound mail (SMTP port 25) is not blocked.
✓  IP address is not blacklisted by zen.spamhaus.org.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "management/status_checks.py", line 342, in run_domain_checks_on_domain
    check_web_domain(domain, rounded_time, ssl_certificates, env, output)
  File "management/status_checks.py", line 631, in check_web_domain
    value = query_dns(domain, rtype)
  File "management/status_checks.py", line 683, in query_dns
    return "; ".join(sorted(str(r).rstrip('.') for r in response))
  File "management/status_checks.py", line 683, in <genexpr>
    return "; ".join(sorted(str(r).rstrip('.') for r in response))
TypeError: __str__ returned non-string (type bytes)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "management/status_checks.py", line 940, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "management/status_checks.py", line 65, in run_checks
    run_domain_checks(rounded_values, env, output, pool)
  File "management/status_checks.py", line 312, in run_domain_checks
    ret = pool.starmap(run_domain_checks_on_domain, args, chunksize=1)
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
TypeError: __str__ returned non-string (type bytes)
```

Any ideas? 

Thanks in advance,
-G.

**Comment by JoshData** [comment]
Moving to #945.
