### ISSUE TITLE
Fix "Status checks for ufw ... " seems not be fixed

### ISSUE THREAD

**Issue by h8h** [mail-in-a-box/mailinabox#987]
Hi, 

I accidently installed ufw and removed it afterwards. My system doesn't support iptables. 

From now on I get this error message:

```
Traceback (most recent call last):
  File "management/status_checks.py", line 966, in <module>
    run_and_output_changes(env, pool)
  File "management/status_checks.py", line 822, in run_and_output_changes
    run_checks(True, env, cur, pool)
  File "management/status_checks.py", line 64, in run_checks
    run_network_checks(env, output)
  File "management/status_checks.py", line 269, in run_network_checks
    check_ufw(env, output)
  File "management/status_checks.py", line 172, in check_ufw
    code, ufw = shell('check_output', ['ufw', 'status'], trap=True)
  File "/root/mailinabox/management/utils.py", line 196, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ufw'
```

I'm using the v0.20 tag and patched the fix #961 manually. 

The fix patched only the management/status_checks.py but the error occures in the utils.py file.

I can reproduce the error with the following commands

```
~# cd /root/mailinabox/management
~# python3
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from utils import shell, sort_domains, load_env_vars_from_file, load_settings
>>> code, ufw = shell('check_output', ['ufw', 'status'], trap=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/mailinabox/management/utils.py", line 196, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ufw'
```

From the  [subprocess manpage](https://docs.python.org/3.4/library/subprocess.html#security-considerations):
> If shell is True, the specified command will be executed through the shell. 

If I add ``kwargs['shell'] = True`` the output is:
```
status: 1: status: ufw: not found
```
But `shell = True` is a security hazard 

> Note
> Read the Security Considerations section before using shell=True. 

and further:
> It is the application’s responsibility to ensure that all whitespace and metacharacters are quoted appropriately to avoid shell injection vulnerabilities.

We don't construct a string from external input so I think we can saftely use `shell=True` or is there another option?

**Comment by yodax** [comment]
We can also check if the ufw command is present before running the command.

**Comment by yodax** [comment]
```
diff --git a/management/status_checks.py b/management/status_checks.py
index f138b5e..060244f 100755
--- a/management/status_checks.py
+++ b/management/status_checks.py
@@ -169,6 +169,11 @@ def run_system_checks(rounded_values, env, output):
        check_free_memory(rounded_values, env, output)
 
 def check_ufw(env, output):
+       if not os.path.isfile('/usr/sbin/ufw'):
+               output.print_warning("""The firewall is not installed on this machine. The ufw program was not 
+                                       installed. Please rerun the setup.""")
+               return
+
        code, ufw = shell('check_output', ['ufw', 'status'], trap=True)
 
        if code != 0:

```

Could you give this a go?

**Comment by h8h** [comment]
Yes. 

`check_output` should only check the output and shouldn't care if the command exists. 

So checking beforehand if the command exits is a good idea.

Thank you.

It could be a bit confusing to say, hey your firewall is not installed, rerun setup. Maybe we should write something like this: 
```
The ufw program was not installed. If your system is able to run iptables, rerun the setup.
```

**Comment by yodax** [comment]
I changed the message and created a PR for this. Thanks for the report!

**Comment by h8h** [comment]
Thank you.
